### PR TITLE
trivial: venv: check build.ninja presence

### LINKED ISSUE #7227: Build gets stuck if Vala is not installed
**Describe the bug**
After I saw a request to build fwupd from source [on Mastodon](https://mastodon.social/@hughsie/112412001905663059) and tried it out, I noticed that the build can get into an undesirable state if a dependency is initially missing, requiring additional action even after the build dependency is installed.

**Steps to Reproduce**
(These are the steps I followed, but if you follow the same steps, I expect you might get a different result depending on your system.)
- Environment: Arch Linux, with an assortment of development-related packages installed but without Vala
- Clone https://github.com/fwupd/fwupd/
- Run `contrib/setup` as mentioned on Mastodon
  - Do not install build dependencies (the default)
  - Do not run tests locally before pushing (the default)
- Run `source venv/bin/activate` as advised by setup’s output
- Run `build-fwupd` as advised by activate’s output
  > Program vapigen found: NO
  > 
  > libfwupd/meson.build:159:8: ERROR: Program 'vapigen' not found or not executable
- Look up which package is supposed to supply `vapigen` (the [Arch manpage](https://man.archlinux.org/man/vapigen-0.56.1.en) shows the package in the sidebar), then install Vala with `sudo pacman -S vala`
- Run `build-fwupd` again

**Expected behavior**
The build resumes, and ideally completes successfully.

**Actual behavior**
The command instantly (0.006 s real time) fails (exit code 1) with:
```
ninja: Entering directory `/tmp/fwupd/venv/bin/../build'
ninja: error: loading 'build.ninja': No such file or directory
```

To make the build work again, I have to remove `venv/build/`; after that, `build-fwupd` mostly works. (Towards the end, the installation fails with `find: ‘/usr/libexec/fwupd/efi’: No such file or directory`, but I assume that’s unrelated.)

**fwupd version information**
Git commit 664e94bfca.

```shell
$ fwupdmgr --version
compile   org.freedesktop.fwupd         1.9.19
compile   com.hughsie.libxmlb           0.3.19
compile   org.freedesktop.Passim        0.1.8
compile   com.hughsie.libjcat           0.2.1
runtime   org.freedesktop.fwupd-efi     1.6
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libxmlb           0.3.19
runtime   org.freedesktop.Passim        0.1.8
runtime   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.1
runtime   org.kernel                    6.8.9-arch1-1
runtime   org.freedesktop.fwupd         1.9.19
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): source under Arch, as above.

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
$ fwupdmgr get-devices --show-all-devices
WARNING: This package has not been validated, it may not work properly.
Unsupported daemon version 1.9.19, client version is 1.9.10-805-g664e94bfca
```

Let me know if you want the output of some similar command anyway (e.g. using system `fwupdmgr` instead of the built-from-source one), but I suspect it’s not actually relevant for this issues.

</details>

**Additional questions**

- Operating system and version: Arch Linux
- Have you tried rebooting? no
- Is this a regression? not to my knowledge

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
If Meson failed partway through, it’s possible that the build directory exists but build.ninja inside doesn’t, which would make Ninja fail immediately. Fixes #7227.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

File: contrib/build-venv.sh [hunk 1]
```diff
@@ -9,7 +9,7 @@ EXTRA_ARGS="-Dsystemd=disabled -Dlaunchd=disabled"
 if [ -d /opt/homebrew/opt/libarchive/lib/pkgconfig ]; then
         EXTRA_ARGS="${EXTRA_ARGS} -Dpkg_config_path=/opt/homebrew/opt/libarchive/lib/pkgconfig"
 fi
-if [ ! -d ${BUILD} ]; then
+if [ ! -d ${BUILD} ] || ! [ -e ${BUILD}/build.ninja ]; then
```
Comment (lucaswerkmeister) [inline contrib/build-venv.sh:12]: The first part of the check could also be removed, I guess (`[ -e ${BUILD}/build.ninja ]` will also be silently false if the build dir doesn’t exist). I don’t have an opinion on which is better, happy to change it either way.

**Review by superm1 — APPROVED** [review]
