### PR TITLE
fix fu_chunk_array_new may hand and timeout

### LINKED ISSUE #9291: App hand and timeout when calling fu_chunk_array_new(NULL, 65536, 0, 65536, 4096)
https://github.com/fwupd/fwupd/blob/0f1dbcb6959545776544caf57915cd5b0317362e/libfwupdplugin/fu-chunk.c#L441-L445
 
`chunksz` becomes to 0.

### PR DESCRIPTION
**Pull request by adamgene**
To fix #9291 

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

because `offset + packet_sz` may align to `page_sz` then cause `chunksz` become 0.

### CODE REVIEW

File: libfwupdplugin/fu-chunk.c [hunk 1]
```diff
@@ -438,8 +438,11 @@ fu_chunk_array_new(const guint8 *data,
 		}
 
 		/* cut the packet so it does not straddle multiple blocks */
-		if (page_sz != packet_sz && page_sz > 0)
-			chunksz = MIN(chunksz, (offset + packet_sz) % page_sz);
+		if (page_sz != packet_sz && page_sz > 0) {
+			gsize chunksz_tmp = MIN(chunksz, (offset + packet_sz) % page_sz);
+			if (chunksz_tmp != 0)
+				chunksz = chunksz_tmp;
```
Comment (hughsie) [inline libfwupdplugin/fu-chunk.c:446]: can you also add a test to `libfwupdplugin/fu-self-test.c` please? i.e. copy fu_chunk_array_func and add one that this bug would fix. Also, in general commit messages normally start with a capital letter, unless we're using a prefix like `trivial: ` -- thanks. I think a good commit message for this would be something like `Fix a potential hang when creating a chunk array with unusual page sizes` or something like that.

Comment (adamgene) [reply libfwupdplugin/fu-chunk.c:446]: I'm not sure the difference between `FuChunkArray` and array of `FuChunk`. I saw the test of `fu_chunk_array_new` is in fu_chunk_func, should I add test info this?

Comment (hughsie) [reply libfwupdplugin/fu-chunk.c:446]: FuChunkArray is much more memory efficient wen there are a large number of blocks -- but doesn't support pages.

> should I add test info this

Create a new fu_chunk_array_null_func please -- more simple tests are better than one big complex test.
