### PR TITLE
snapd-uefi: Fix request when multiple updates are in the composite

### LINKED ISSUE #9863: fu-snapd-uefi-plugin sends zip of updates to snapd which expects a signature list
This on the Canonical side to fix this issue. However I open an issue here just to have some input from you so that we do not get too much confusion on what should be fixed.

I suspect the issue is because this is handling incorrectly a composite update. And we should either do:
 * Do not do composite, but do the request before every signature list.
 * Or handle composite in snapd, but  we will need to understand the order updates will be applied. Then we will need to reseal keys for "no update" , "update1", "update 1" + "update 2", "update 1" + "update 2" + "update 3", ... So that if we reboot in the middle of update, we can still unlock the disk.

cc @BAMF0 @bboozzoo 

**Describe the bug**

For 2023 UEFI db update, fu-snapd-uefi-plugin sends to snapd a firmware that is zip containing both DBUpdate3P2023.bin and DBUpdateOROM2023.bin. However snapd expects a signature list here.

**Steps to Reproduce**

On a system with snapd handling uefi updates (that is with TPM backed FDE), apply "UEFI CA (2011 → 2023)". 

**Expected behavior**

Snapd will fail.

**fwupd version information**

Ubuntu package 2.0.19-1

```
compile   info.libusb                   1.0.29
compile   org.freedesktop.fwupd         2.0.19
compile   com.hughsie.libxmlb           0.3.24
compile   com.hughsie.libjcat           0.2.5
runtime   org.freedesktop.fwupd-efi     1.7
runtime   com.hughsie.libxmlb           0.3.24
runtime   com.hughsie.libjcat           0.2.5
runtime   org.kernel                    6.8.0-86-generic
runtime   org.freedesktop.fwupd         2.0.19
```

I skip the rest. It is just a qemu VM with OVMF + swtpm.

### PR DESCRIPTION
**Pull request by valentindavid**
Snapd needs to be given the firmware updates in the right order.  The change of API will come in snapd 2.74.1 or 2.74.2.  Though since giving the composite update at once as zip does not work on any version. So it is safe to just try to use the new API when multiple updates are to be applied.

New snapd API in canonical/snapd#16541

Fixes #9863

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

File: plugins/snapd-uefi/fu-snapd-uefi-plugin.c [hunk 1]
```diff
@@ -263,25 +263,45 @@ fu_snapd_uefi_plugin_composite_peek_firmware(FuPlugin *plugin,
...
+		if (fw == NULL)
+			return FALSE;
+		buf = g_bytes_get_data(fw, &bufsz);
+		b64data = g_base64_encode(buf, bufsz);
+		fwupd_json_object_add_string(json_obj, "payload", b64data);
+	} else {
+		g_autoptr(FwupdJsonArray) json_arr = fwupd_json_array_new();
+
+		for (guint i = 0; i < images->len; i++) {
+			g_autoptr(GBytes) fw = NULL;
```
Comment (hughsie) [inline plugins/snapd-uefi/fu-snapd-uefi-plugin.c]: i think you need to move `g_autofree gchar *b64data` here to avoid leaking.

Comment (hughsie) [reply plugins/snapd-uefi/fu-snapd-uefi-plugin.c]: Maybe adding something to the libfwupd API might be a good idea? e.g. `fwupd_json_object_add_bytes()` and `fwupd_json_array_add_bytes(GBytes)`?

File: libfwupd/fwupd-json-array.c [hunk 2]
```diff
@@ -331,6 +331,31 @@ fwupd_json_array_add_array(FwupdJsonArray *self, FwupdJsonArray *json_arr)
...
+ *
+ * Adds bytes to a JSON array. They will be base64 encoded as a string.
+ *
+ * Since: 2
+ **/
+void
+fwupd_json_array_add_bytes(FwupdJsonArray *self, GBytes *value)
+{
+        g_autofree gchar *b64data = NULL;
+	const guint8 *buf;
```
Comment (hughsie) [inline libfwupd/fwupd-json-array.c:347]: indenting looks funky; did you do ./contrib/setup to set up precommit? if not, you can reformat with clang-format.

File: libfwupd/fwupd.map [hunk 3]
```diff
@@ -1087,6 +1088,7 @@ LIBFWUPD_2.1.1 {
     fwupd_json_object_add_object_map;
     fwupd_json_object_add_raw;
     fwupd_json_object_add_string;
+    fwupd_json_object_add_bytes;
```
Comment (hughsie) [inline libfwupd/fwupd.map]: can you add some simple tests in libfwupd/fwupd-json-test.c please for coverage.

**Comment by superm1** [comment]
Will there be an API to check whether support is there in snapd?  If so, should the plugin look for it and fail to init if missing?

**Comment by valentindavid** [comment]
> Will there be an API to check whether support is there in snapd? If so, should the plugin look for it and fail to init if missing?

I do not know if we should fail completely when updates with one blob only work. What we can do some better error message at best. But we could also do that by just showing the error returned by snapd instead of the error code only.
