### PR TITLE
Modem modemanger udev context

### LINKED ISSUE #4110: modem-manager: modem gets not uninhibited
# Description

Upgrading modems using fwupd's modem-manager and fastboot plugins works, but ModemManager is afterwards not seeing the modem as it is still marked as 'inhibited'. Actually ModemManager sees it, but doesn't expose it as the modem was marked as inhibited:

**ModemManager log snippet**
```
[5168]: <debug> [1639768715.339353] [base-manager] adding port ttyUSB0 at sysfs path: /sys/devices/platform/soc/1c1b000.usb/usb2/2-1/2-1:1.0/ttyUSB0/tty/ttyUSB0
[5168]: <debug> [1639768715.339777] [base-manager] added port ttyUSB0 while inhibited
[5168]: <debug> [1639768715.367745] [ttyUSB2] port contents loaded:
[5168]: <debug> [1639768715.367915] [ttyUSB2]   bus: usb
[5168]: <debug> [1639768715.367970] [ttyUSB2]   interface: /sys/devices/platform/soc/1c1b000.usb/usb2/2-1/2-1:1.2
[5168]: <debug> [1639768715.368024] [ttyUSB2]   device: /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
[5168]: <debug> [1639768715.368077] [ttyUSB2]   driver: option
[5168]: <debug> [1639768715.368125] [ttyUSB2]   vendor: 2c7c
[5168]: <debug> [1639768715.368175] [ttyUSB2]   product: 0125
[5168]: <debug> [1639768715.368222] [ttyUSB2]   revision: 0318
[5168]: <debug> [1639768715.368286] [base-manager] adding port ttyUSB2 at sysfs path: /sys/devices/platform/soc/1c1b000.usb/usb2/2-1/2-1:1.2/ttyUSB2/tty/ttyUSB2
[5168]: <debug> [1639768715.368774] [base-manager] added port ttyUSB2 while inhibited
```

**Upgrade process:**
- modem-manager plugin: mark modem as inhibited in ModemManager so fwupd can do the upgrade
- modem-manager plugin: handover to fastboot plugin
- fastboot plugin: do upgrade
- modem-manager plugin: mark modem as uninhibited so ModemManager controls again the modem

However, this last step seems to be missing and I think it is because of the missing context (as this was also the case for private flags in #4076 and the same thing shows up in the logs: `no FuContext assigned for FuMmDevice`) , but I'm not sure where this is supposed to happen as the only place where a device is constructed (`fu-plugin-modem-manager.c`) has the context fix.

**Workaround**

Restarting ModemManager works around the issue as ModemManager forgets then the inhibited state.

# Logs

```
19:15:12:0727 FuMain               Emitting PropertyChanged('Percentage'='92%')
19:15:55:0140 FuMain               Emitting PropertyChanged('Percentage'='93%')
19:16:37:0555 FuMain               Emitting PropertyChanged('Percentage'='94%')
19:17:19:0971 FuMain               Emitting PropertyChanged('Percentage'='95%')
19:18:02:0383 FuMain               Emitting PropertyChanged('Percentage'='96%')
19:18:04:0157 FuPluginFastboot     ignoring transfer timed out
19:18:05:0411 FuPluginFastboot     ignoring transfer timed out
19:18:06:0665 FuPluginFastboot     ignoring transfer timed out
19:18:07:0919 FuPluginFastboot     ignoring transfer timed out
19:18:09:0173 FuPluginFastboot     ignoring transfer timed out
19:18:10:0428 FuPluginFastboot     ignoring transfer timed out
19:18:11:0682 FuPluginFastboot     ignoring transfer timed out
19:18:12:0936 FuPluginFastboot     ignoring transfer timed out
19:18:14:0190 FuPluginFastboot     ignoring transfer timed out
19:18:15:0444 FuPluginFastboot     ignoring transfer timed out
19:18:16:0698 FuPluginFastboot     ignoring transfer timed out
19:18:17:0953 FuPluginFastboot     ignoring transfer timed out
19:18:19:0207 FuPluginFastboot     ignoring transfer timed out
19:18:19:0458 FuHistory            modifying device Fastboot MDM9607 [cf294bf55b333004beb7c41f952c1838c23e1f4a]
19:18:19:0461 FuHistory            modifying device Fastboot MDM9607 [cf294bf55b333004beb7c41f952c1838c23e1f4a]
19:18:19:0462 FuMain               Emitting PropertyChanged('Status'='device-restart')
19:18:19:0462 FuDeviceList         no replug or re-enumerate required
19:18:19:0464 FuEngine             attach -> FuFastbootDevice:
  DeviceId:             cf294bf55b333004beb7c41f952c1838c23e1f4a
  Name:                 Fastboot MDM9607
  Guid:                 477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9 <- USB\VID_18D1&PID_D00D&REV_0100
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039 <- USB\VID_18D1&PID_D00D
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec
  Serial:               700a421b
  Summary:              Quectel EG25-G modem (fastboot)
  Plugin:               fastboot
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|is-bootloader|add-counterpart-guids|has-multiple-branches
  Vendor:               Google
  VendorId:             USB:0x18D1
  VendorId:             USB:0x2C7C
  Version:              1.0
  VersionFormat:        bcd
  Created:              2021-12-17
  UpdateState:          success
  PhysicalId:           usb:02:00:01
  CustomFlags:          detach-at-fastboot-has-no-response
  Order:                0
  ParentPhysicalIds:    usb:02:00,usb:02
  InternalFlags:        replug-match-guid
  PrivateFlags:
  InterfaceNumber:      0x0
  BlockSize:            0x4000
  Secure:               false

19:18:19:0464 FuPlugin             attach(fastboot)
19:18:19:0967 FuDeviceLocker       failed to close device: failed to release interface: USB error on device 18d1:d00d : No such device (it may have been disconnected) [-4]
19:18:19:0967 FuMain               Emitting PropertyChanged('Status'='device-busy')
19:18:19:0968 FuMain               Emitting PropertyChanged('Percentage'='98%')
19:18:19:0969 FuDeviceList         waiting 60000ms for replug
19:18:19:0970 FuEngine             auto-removing backend device Fastboot MDM9607 [cf294bf55b333004beb7c41f952c1838c23e1f4a]
19:18:19:0972 FuDeviceList         waiting 60000ms for Fastboot MDM9607 device removal
19:18:21:0720 FuDevice             no registered custom flag detach-at-fastboot-has-no-response on FuUsbDevice
19:18:21:0732 FuDevice             no registered custom flag detach-at-fastboot-has-no-response on FuFastbootDevice
19:18:21:0738 FuDevice             no registered custom flag detach-at-fastboot-has-no-response on FuFastbootDevice
19:18:21:0738 FuDevice             using cf294bf55b333004beb7c41f952c1838c23e1f4a for usb:02:00:01
19:18:22:0246 FuDevice             cf294bf55b333004beb7c41f952c1838c23e1f4a device overwriting name value: Android->Fastboot MDM9607
19:18:22:0748 FuPluginFastboot     fastboot version=0.5
19:18:24:0252 FuPlugin             emit added from fastboot: cf294bf55b333004beb7c41f952c1838c23e1f4a
19:18:24:0286 XbSilo               ignoring for OR statement: indexed string '477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9' was unfound
19:18:24:0287 XbSilo               ignoring for OR statement: indexed string 'db379a33-254f-5140-b37e-d36ae7e5c039' was unfound
19:18:24:0287 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0287 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0294 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0294 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0300 FuPlugin             fu_plugin_device_registered(dell_dock)
19:18:24:0300 FuPlugin             fu_plugin_device_registered(pci_bcr)
19:18:24:0300 FuPlugin             fu_plugin_device_registered(thunderbolt)
19:18:24:0300 FuPlugin             fu_plugin_device_registered(tpm)
19:18:24:0300 FuDeviceList         found existing device cf294bf55b333004beb7c41f952c1838c23e1f4a
19:18:24:0300 FuDeviceList         copying update state success to new device
19:18:24:0301 FuDeviceList         ::changed cf294bf55b333004beb7c41f952c1838c23e1f4a
19:18:24:0319 XbSilo               ignoring for OR statement: indexed string '477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9' was unfound
19:18:24:0319 XbSilo               ignoring for OR statement: indexed string 'db379a33-254f-5140-b37e-d36ae7e5c039' was unfound
19:18:24:0319 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0319 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0322 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0322 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0329 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:18:24:0330 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:18:24:0345 XbSilo               ignoring for OR statement: indexed string '477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9' was unfound
19:18:24:0345 XbSilo               ignoring for OR statement: indexed string 'db379a33-254f-5140-b37e-d36ae7e5c039' was unfound
19:18:24:0346 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0346 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0352 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0352 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0354 FuEngine             client does not understand branches, skipping biktorgj-002:PINEPHONE_MODEM_SDK_0.4.9-002
19:18:24:0355 FuEngine             ignoring EG25GGBR07A08M2G - 05010820 < 1.0
19:18:24:0355 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:18:24:0355 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:18:24:0369 XbSilo               ignoring for OR statement: indexed string '477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9' was unfound
19:18:24:0369 XbSilo               ignoring for OR statement: indexed string 'db379a33-254f-5140-b37e-d36ae7e5c039' was unfound
19:18:24:0370 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0370 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0373 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0373 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0375 FuEngine             client does not understand branches, skipping biktorgj-002:PINEPHONE_MODEM_SDK_0.4.9-002
19:18:24:0376 FuEngine             writing motd target /var/cache/fwupd/motd.d/85-fwupd
19:18:24:0376 FuDeviceList         waited for replug
19:18:24:0377 FuEngine             reload -> FuFastbootDevice:
  DeviceId:             cf294bf55b333004beb7c41f952c1838c23e1f4a
  Name:                 Fastboot MDM9607
  Guid:                 477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9 <- USB\VID_18D1&PID_D00D&REV_0100
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039 <- USB\VID_18D1&PID_D00D
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3
  Serial:               700a421b
  Summary:              Quectel EG25-G modem (fastboot)
  Plugin:               fastboot
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|is-bootloader|add-counterpart-guids|has-multiple-branches
  Vendor:               Google
  VendorId:             USB:0x18D1
  Version:              1.0
  VersionFormat:        bcd
  Created:              2021-12-17
  UpdateState:          success
  PhysicalId:           usb:02:00:01
  CustomFlags:          detach-at-fastboot-has-no-response
  Order:                0
  ParentPhysicalIds:    usb:02:00,usb:02
  InternalFlags:        replug-match-guid
  InterfaceNumber:      0x0
  BlockSize:            0x4000
  Secure:               false

19:18:24:0378 FuMain               Emitting PropertyChanged('Status'='unknown')
19:18:24:0378 FuMain               Emitting PropertyChanged('Percentage'='100%')
19:18:24:0379 FuProgress           raw timing data was { 0.068, 1871.543, 0.506, 4.410 } -- steps were set as [ 2 94 2 2 ] but should have been [ 0 100 0 0 ] at ../plugins/modem-manager/fu-mm-device.c:1510
19:18:24:0379 FuProgress           Please see https://github.com/fwupd/fwupd/wiki/Daemon-Warning:-FuProgress-steps
19:18:24:0379 FuDeviceList         no replug or re-enumerate required
19:18:24:0379 FuDeviceList         no replug or re-enumerate required
19:18:24:0379 FuEngine             cleanup -> FuFastbootDevice:
  DeviceId:             cf294bf55b333004beb7c41f952c1838c23e1f4a
  Name:                 Fastboot MDM9607
  Guid:                 477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9 <- USB\VID_18D1&PID_D00D&REV_0100
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039 <- USB\VID_18D1&PID_D00D
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3
  Serial:               700a421b
  Summary:              Quectel EG25-G modem (fastboot)
  Plugin:               fastboot
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|is-bootloader|add-counterpart-guids|has-multiple-branches
  Vendor:               Google
  VendorId:             USB:0x18D1
  Version:              1.0
  VersionFormat:        bcd
  Created:              2021-12-17
  UpdateState:          success
  PhysicalId:           usb:02:00:01
  CustomFlags:          detach-at-fastboot-has-no-response
  Order:                0
  ParentPhysicalIds:    usb:02:00,usb:02
  InternalFlags:        replug-match-guid
  InterfaceNumber:      0x0
  BlockSize:            0x4000
  Secure:               false

19:18:24:0380 FuPlugin             cleanup(jabra)
19:18:24:0380 FuPlugin             cleanup(logind)
19:18:24:0381 FuPluginLogind       closed logind fd 15
19:18:24:0381 FuDeviceList         no replug or re-enumerate required
19:18:24:0381 FuEngine             Updating QUECTEL Mobile Broadband Module took 1876.538651 seconds
19:18:24:0382 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:18:24:0382 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:18:24:0393 XbSilo               ignoring for OR statement: indexed string '477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9' was unfound
19:18:24:0394 XbSilo               ignoring for OR statement: indexed string 'db379a33-254f-5140-b37e-d36ae7e5c039' was unfound
19:18:24:0394 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0395 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0397 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0397 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0400 FuEngine             client does not understand branches, skipping biktorgj-002:PINEPHONE_MODEM_SDK_0.4.9-002
19:18:24:0400 FuEngine             ignoring EG25GGBR07A08M2G - 05010820 < 1.0
19:18:24:0400 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:18:24:0401 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:18:24:0411 XbSilo               ignoring for OR statement: indexed string '477cfbab-cc6d-5fff-9aa0-e72f6bf52aa9' was unfound
19:18:24:0412 XbSilo               ignoring for OR statement: indexed string 'db379a33-254f-5140-b37e-d36ae7e5c039' was unfound
19:18:24:0412 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0412 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0415 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:24:0415 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:24:0418 FuEngine             client does not understand branches, skipping biktorgj-002:PINEPHONE_MODEM_SDK_0.4.9-002
19:18:24:0418 FuEngine             writing motd target /var/cache/fwupd/motd.d/85-fwupd
19:18:24:0418 FuPlugin             composite_cleanup(dell_dock)
19:18:24:0419 FuPlugin             composite_cleanup(thunderbolt)
19:18:24:0419 FuIdle               uninhibiting: update
19:18:24:0429 FuMain               Called GetRemotes()
19:18:25:0018 FuEngine             auto-removing backend device Fastboot MDM9607 [cf294bf55b333004beb7c41f952c1838c23e1f4a]
19:18:25:0020 FuDeviceList         waiting 60000ms for Fastboot MDM9607 device removal
19:18:34:0323 FuContext            battery level now 97
19:18:35:0264 FuDevice             no registered custom flag detach-at-fastboot-has-no-response on FuUsbDevice
19:18:35:0327 FuPluginMm           added port to inhibited modem: /dev/ttyUSB1 (ifnum 1)
19:18:35:0327 FuPluginMm           creating udev-based mm device at /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
19:18:35:0327 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Summary:              Mobile broadband device
  Flags:                updatable|require-ac|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

19:18:35:0328 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Summary:              Mobile broadband device
  Flags:                updatable|require-ac|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

19:18:35:0328 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9
  Summary:              Mobile broadband device
  Flags:                updatable|require-ac|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

19:18:35:0328 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3
  Summary:              Mobile broadband device
  Flags:                updatable|require-ac|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

19:18:35:0329 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec
  Summary:              Mobile broadband device
  Flags:                updatable|require-ac|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

19:18:35:0329 FuPluginMm           ignoring port /dev/ttyUSB1 (tty)
19:18:35:0330 FuPluginMm           added port to inhibited modem: /dev/ttyUSB3 (ifnum 3)
19:18:35:0330 FuPluginMm           ignoring port /dev/ttyUSB3 (tty)
19:18:35:0331 FuPluginMm           added port to inhibited modem: /dev/cdc-wdm0 (ifnum -1)
19:18:35:0332 FuPluginMm           ignoring port /dev/cdc-wdm0 (usbmisc)
19:18:35:0338 FuPluginMm           added port to inhibited modem: /dev/ttyUSB0 (ifnum 0)
19:18:35:0338 FuPluginMm           ignoring port /dev/ttyUSB0 (tty)
19:18:35:0367 FuPluginMm           added port to inhibited modem: /dev/ttyUSB2 (ifnum 2)
19:18:35:0367 FuPluginMm           added AT port /dev/ttyUSB2 (tty)
19:18:38:0256 FuDevice             using 976c4a39e87f61e6940ea6a8d39c583cfa99615f for /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
19:18:38:0256 FuPlugin             emit added from modem_manager: 976c4a39e87f61e6940ea6a8d39c583cfa99615f
19:18:38:0256 FuEngine             device 976c4a39e87f61e6940ea6a8d39c583cfa99615f [QUECTEL Mobile Broadband Module] does not define an update protocol
19:18:38:0291 XbSilo               ignoring for OR statement: indexed string 'db379a33-254f-5140-b37e-d36ae7e5c039' was unfound
19:18:38:0355 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:38:0355 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:38:0358 FuEngine             requirement 1.7.4 ge 1.7.4 -> org.freedesktop.fwupd passed
19:18:38:0358 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:18:38:0362 FuPlugin             fu_plugin_device_registered(dell_dock)
19:18:38:0363 FuPlugin             fu_plugin_device_registered(pci_bcr)
19:18:38:0363 FuPlugin             fu_plugin_device_registered(thunderbolt)
19:18:38:0363 FuPlugin             fu_plugin_device_registered(tpm)
19:18:38:0363 FuDeviceList         found old device 976c4a39e87f61e6940ea6a8d39c583cfa99615f, swapping
19:18:38:0363 FuDeviceList         copying update state success to new device
19:18:38:0367 FuDeviceList         ::changed 976c4a39e87f61e6940ea6a8d39c583cfa99615f
19:18:38:0370 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:18:38:0371 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:18:38:0372 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:18:38:0372 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:18:38:0372 FuEngine             writing motd target /var/cache/fwupd/motd.d/85-fwupd
```

# Testing environment

- Pine64 PinePhone
- postmarketOS edge
- ModemManager 1.18.4
- fwupd db94a995bd94600af98933eacc957cdbec27bf41

### PR DESCRIPTION
**Pull request by DylanVanAssche**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

# Changes

## Pass context with udev based discovery as well

When a modem is discovered through udev after upgrading it, the context was not passed.
This resulted in the following messages in the log:
```
FuDevice             no FuContext assigned for FuMmDevice:
```
Passing the context fixes it.

## Uninhibit modem after upgrading

ModemManager gives all controls to fwupd when upgrading by inhibiting the modem through the modem-manager plugin.
However, after upgrading, the controls should be given back to ModemManager by uninhibiting the modem. That last part was missing in the case of udev discovery. Because of this, ModemManager saw the modem but didn't expose it as it remained inhibited. Restarting ModemManager or rebooting the device worked around the issue, but didn't solve the cause of it.

Therefore, uninhibit as well when a modem is rediscovered through udev and solve a segfault as well in the mean time due to `g_autofree` and `g_steal_pointer`. They stole a pointer which was still necessary for the rest of the uninhibiting part.
I could reproduce this continuously when the method was invoked.

# Issues

Fixes #4110 

# Test environment

- Pine64 PinePhone
- Quectel EG25-G modem
- postmarketOS edge
- fwupd db94a995bd94600af98933eacc957cdbec27bf41

### CODE REVIEW

**Comment by hughsie** [comment]
I've merged the context one to main, thanks. @aleksander0m can you sanity check the uninhibit one please.

File: plugins/modem-manager/fu-plugin-modem-manager.c [hunk 1]
```diff
@@ -60,17 +60,20 @@ static void
...
-		g_debug("uninhibit modemmanager device with uid %s", info->inhibited_uid);
-		mm_manager_uninhibit_device_sync(priv->manager, info->inhibited_uid, NULL, NULL);
+	if ((priv->manager != NULL) && (priv->inhibited != NULL)) {
+		g_debug("uninhibit modemmanager device with uid %s",
+			priv->inhibited->inhibited_uid);
+		mm_manager_uninhibit_device_sync(priv->manager,
+						 priv->inhibited->inhibited_uid,
+						 NULL,
+						 NULL);
 	}
```
Comment (hughsie) [inline plugins/modem-manager/fu-plugin-modem-manager.c:77]: I don't think this is right; the original code cleaned up priv->inhibited.

Comment (DylanVanAssche) [reply plugins/modem-manager/fu-plugin-modem-manager.c:77]: Hmmmm that's true because we don't do `g_steal_pointer` anymore.
What about cleaning it up in `fu_plugin_mm_inhibit_device`?
Right before we do `g_steal_pointer` there, free the value if there is one?

```
diff --git a/plugins/modem-manager/fu-plugin-modem-manager.c b/plugins/modem-manager/fu-plugin-modem-manager.c
index 73f5aa44..f4185a63 100644
--- a/plugins/modem-manager/fu-plugin-modem-manager.c
+++ b/plugins/modem-manager/fu-plugin-modem-manager.c
@@ -203,6 +203,7 @@ fu_plugin_mm_inhibit_device(FuPlugin *plugin, FuDevice *device, GError **error)
                return FALSE;
 
        /* setup inhibited device info */
+       g_free(priv->inhibited);
        priv->inhibited = g_steal_pointer(&info);
 
        /* only do modem port monitoring using udev if the module is expected
```

Comment (hughsie) [reply plugins/modem-manager/fu-plugin-modem-manager.c:77]: `priv->inhibited` isn't a single pointer; it's a `FuPluginMmInhibitedDeviceInfo` object, hence the `g_autoptr`. I think the code needs to change back to what it was before tbh.

Comment (DylanVanAssche) [reply plugins/modem-manager/fu-plugin-modem-manager.c]: I reverted the change, retried it a few times and it seems to be fine now. Maybe it got fixed somehow with other commits.
