### PR TITLE
Fall back to FAT32 internal partitions for detecting ESP

### LINKED ISSUE #2576: UEFI warning always printed even if uefi plugin is not built on ppc64
**Describe the bug**
the following warning is always printed on `ppc64` platform.
```
WARNING: UEFI capsule updates not available or enabled
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
```
of course `fwupd` is built without uefi support.
I tried also adding `DisabledPlugins=test;invalid;uefi` to config file, just in case, warning is still printed on every `fwupdmgr` invocation.

**Steps to Reproduce**
Steps to reproduce the behavior.
run `fwupdmgr`, warning printed every time despite efi support is not even built in.

**Expected behavior**
No warning printed.

**fwupd version information**
```shell
$ fwupdmgr --version
client version: 1.5.1
compile-time dependency versions
        gusb:   0.3.5

daemon version: 1.5.1
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
installed via emerge (gentoo package manager)

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
$ fwupdmgr get-devices --show-all-devices
```

**Additional questions**
- Operating system and version:
gentoo rolling ppc64le
- Have you tried rebooting?
irrelevant, but yes
- Is this a regression?
I haven't checked previous versions.

### PR DESCRIPTION
**Pull request by superm1**
Fixes #2576

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

File: libfwupdplugin/fu-common.c [hunk 1]
```diff
@@ -2284,11 +2281,18 @@ fu_common_get_volumes_by_kind (const gchar *kind, GError **error)
...
-					       "proxy-block", proxy_blk,
-					       "proxy-filesystem", proxy_fs,
-					       NULL));
+		vol = g_object_new (FU_TYPE_VOLUME,
+				    "proxy-block", proxy_blk,
+				    "proxy-filesystem", proxy_fs,
+				    NULL);
+		g_debug ("device %s, type: %s, internal: %d",
+			 g_dbus_proxy_get_object_path (proxy_blk), type_str,
+			fu_volume_is_internal (vol));
```
Comment (hughsie) [inline libfwupdplugin/fu-common.c:2290]: indenting is weird here

File: libfwupdplugin/fu-common.c [hunk 2]
```diff
@@ -2284,11 +2281,18 @@ fu_common_get_volumes_by_kind (const gchar *kind, GError **error)
...
+		if (g_strcmp0 (type_str, kind) != 0)
+			continue;
+		if (!fu_volume_is_internal (vol))
+			continue;
+		g_ptr_array_add (volumes, g_steal_pointer(&vol));
```
Comment (hughsie) [inline libfwupdplugin/fu-common.c:2295]: space after the bracket pls

File: libfwupdplugin/fu-common.c [hunk 3]
```diff
@@ -2401,15 +2405,20 @@ fu_common_get_esp_default (GError **error)
...
 
-	volumes = fu_common_get_volumes_by_kind (FU_VOLUME_KIND_ESP, error);
-	if (volumes == NULL)
-		return NULL;
+	volumes = fu_common_get_volumes_by_kind (FU_VOLUME_KIND_ESP, &error_local);
+	if (volumes == NULL) {
+		g_debug ("%s, falling back to %s", error_local->message, FU_VOLUME_KIND_FAT32);
+		volumes = fu_common_get_volumes_by_kind (FU_VOLUME_KIND_FAT32, error);
+		if (volumes == NULL)
+			return NULL;
```
Comment (hughsie) [inline libfwupdplugin/fu-common.c:2420]: I do wonder if we should combine the errors before returning? e.g. `g_prefix_error (error, "%s: ", error_local->message);` -- otherwise you're going to get a message about not finding the fallback and not actually have a clue we really wanted the ESP kind.

File: libfwupdplugin/fu-common.c (hunk 1 above)
Comment (superm1) [reply libfwupdplugin/fu-common.c]: fixed

File: libfwupdplugin/fu-common.c (hunk 2 above)
Comment (superm1) [reply libfwupdplugin/fu-common.c]: fixed

File: libfwupdplugin/fu-common.c (hunk 3 above)
Comment (superm1) [reply libfwupdplugin/fu-common.c:2421]: fixed

**Review by hughsie — APPROVED** [review]
