### PR TITLE
dell-dock: bugfix for mst instance id

### LINKED ISSUE #8368: Dell WD19 upgrade issue
**Describe the bug**
update is found and downloaded but cannot perform

**Steps to Reproduce**
sudo fwupdtool get-devices
sudo fwupdtool refresh
sudo fwupdtool get-updates
sudo fwupdtool update

**Expected behavior**
Expected correct upgrade to conclude

**fwupd version information**
Please provide the version of the daemon and client.

```shell
fwupdmgr --version
runtime   org.freedesktop.fwupd         2.0.4
runtime   com.hughsie.libxmlb           0.3.21
compile   com.hughsie.libxmlb           0.3.21
runtime   com.hughsie.libjcat           0.2.2
runtime   org.kernel                    24.2.0
compile   com.hughsie.libjcat           0.2.2
compile   info.libusb                   1.0.27
compile   org.freedesktop.fwupd         2.0.4
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

brew on MacOS

<summary>**fwupd device information**</summary>

Loading?                 [************************************** ]
Apple Mac14,5
?
??WD22TB4:
  ?   Device ID:          b3db560e794a8ceb981cf5118b5818ac75d0eafd
  ?   Summary:            High performance dock
  ?   Current version:    01.01.00.07
  ?   Vendor:             Dell Inc. (USB:0x413C)
  ?   Install Duration:   1 minute
  ?   Serial Number:      BYFXYT3/3135888993113304
  ?   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ? USB\VID_413C&PID_B06E&hub&embedded
  ?   Device Flags:       ? Updatable
  ?                       ? Supported on remote server
  ?                       ? Device stages updates
  ?                       ? Device can recover flash failures
  ?                       ? Device is usable for the duration of the update
  ?                       ? Signed Payload
  ?
  ??RTS5413 in Dell dock:
  ?     Device ID:        0bcab2ad4789ecbcca1bf84409a79681c8c700aa
  ?     Summary:          USB 3.1 Generation 1 Hub
  ?     Current version:  01.22
  ?     Vendor:           Dell Inc. (USB:0x413C)
  ?     Install Duration: 14 seconds
  ?     GUIDs:            b27d25f1-019d-5718-b41a-02ddaefe5577 ? USB\VID_413C&PID_B06F
  ?                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ? USB\VID_413C&PID_B06F&hub
  ?     Device Flags:     ? Updatable
  ?                       ? Supported on remote server
  ?                       ? Device stages updates
  ?                       ? Device is usable for the duration of the update
  ?                       ? Signed Payload
  ?                       ? Can tag for emulation
  ?
  ??USB4 controller in Dell dock:
        Device ID:        71413822e87deae707da948bd4b7e537af463c19
        Summary:          USB4 controller
        Current version:  41.81
        Vendor:           Dell Inc. (USB:0x8087, TBT:0x00D4)
        Install Duration: 46 seconds
        GUIDs:            b3f8b518-ebdd-5969-9b44-6b096eff5b9b ? USB\VID_8087&PID_0B40
                          c6e7a14f-f13c-55e5-99de-d59461db1d27 ? USB\VID_8087&PID_0B40&HUB_0000
        Device Flags:     ? Updatable
                          ? Device stages updates
                          ? Device is usable for the duration of the update
                          ? Signed Payload
                          ? Can tag for emulation

Loading?                 [************************************** ]
Loading?                 [************************************** ]
Devices with no available firmware updates:
 ? USB4 controller in Dell dock
Apple Mac14,5
?
??RTS5413 in Dell dock:
? ?   Device ID:          0bcab2ad4789ecbcca1bf84409a79681c8c700aa
? ?   Summary:            USB 3.1 Generation 1 Hub
? ?   Current version:    01.22
? ?   Vendor:             Dell Inc. (USB:0x413C)
? ?   Install Duration:   14 seconds
? ?   GUIDs:              b27d25f1-019d-5718-b41a-02ddaefe5577 ? USB\VID_413C&PID_B06F
? ?                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ? USB\VID_413C&PID_B06F&hub
? ?   Device Flags:       ? Updatable
? ?                       ? Supported on remote server
? ?                       ? Device stages updates
? ?                       ? Device is usable for the duration of the update
? ?                       ? Signed Payload
? ?                       ? Can tag for emulation
? ?
? ??WD19/WD22 USB 3.1 Generation 1 Controller Update:
?       New version:      01.23
?       Remote ID:        lvfs
?       Release ID:       102057
?       Summary:          Firmware update for WD19/WD22 USB 3.1 Generation 1
?       License:          Proprietary
?       Size:             65.5?kB
?       Created:          2024-11-12
?       Urgency:          High
?       Vendor:           Dell
?       Duration:         14 seconds
?       Release Flags:    ? Trusted metadata
?                         ? Is upgrade
?       Description:
?       -Fixed the issue where there is a noise when you use Dell Pro Stereo Headset UC350. This issue occurs when you open Zoom or Sound settings.
?       Checksum:         cf16c3d1c0adda35a41763b4b112bba915a262f396bfe025481fb896dca5be8c
?
??WD22TB4:
  ?   Device ID:          b3db560e794a8ceb981cf5118b5818ac75d0eafd
  ?   Summary:            High performance dock
  ?   Current version:    01.01.00.07
  ?   Vendor:             Dell Inc. (USB:0x413C)
  ?   Install Duration:   1 minute
  ?   Serial Number:      BYFXYT3/3135888993113304
  ?   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ? USB\VID_413C&PID_B06E&hub&embedded
  ?   Device Flags:       ? Updatable
  ?                       ? Supported on remote server
  ?                       ? Device stages updates
  ?                       ? Device can recover flash failures
  ?                       ? Device is usable for the duration of the update
  ?                       ? Signed Payload
  ?
  ??WD19/WD22 EC Embedded Controller Update:
        New version:      01.01.00.10
        Remote ID:        lvfs
        Release ID:       102053
        Summary:          Firmware update for WD19/WD22 EC
        License:          Proprietary
        Size:             131.0?kB
        Created:          2024-11-12
        Urgency:          High
        Vendor:           Dell
        Duration:         1 minute
        Release Flags:    ? Trusted metadata
                          ? Is upgrade
        Description:
        -Fixed the issue where the system automatically shuts down when you plug or unplug the dock to the system.

        -Fixed the issue where the USB device and Preboot Execution Environment (PXE) boot option are not displayed. This issue occurs when you restart or power on the system and press the F12 key to enter the BIOS Setup or Boot Menu.
        Checksum:         cf16c3d1c0adda35a41763b4b112bba915a262f396bfe025481fb896dca5be8c

Loading?                 [************************************** ]
????????????????????????????????????????????????????????????????????????????????
? Upgrade RTS5413 in Dell dock from 01.22 to 01.23?                            ?
????????????????????????????????????????????????????????????????????????????????
? -Fixed the issue where there is a noise when you use Dell Pro Stereo         ?
? Headset UC350. This issue occurs when you open Zoom or Sound settings.       ?
?                                                                              ?
? RTS5413 in Dell dock must remain connected for the duration of the update    ?
? to avoid damage.                                                             ?
????????????????????????????????????????????????????????????????????????????????
Perform operation? [Y|n]: Y
Erasing?                 [*******************                    ]09:45:03.740 FuEngine             failed to cleanup failed composite action: failed to composite_cleanup using dell_dock: failed to subclass open: no proxy

failed to write-firmware: failed to subclass open: no proxy
????????????????????????????????????????????????????????????????????????????????
? Upgrade WD22TB4 from 01.01.00.07 to 01.01.00.10?                             ?
????????????????????????????????????????????????????????????????????????????????
? -Fixed the issue where the system automatically shuts down when you plug or  ?
? unplug the dock to the system.                                               ?
?                                                                              ?
? -Fixed the issue where the USB device and Preboot Execution Environment      ?
? (PXE) boot option are not displayed. This issue occurs when you restart or   ?
? power on the system and press the F12 key to enter the BIOS Setup or Boot    ?
? Menu.                                                                        ?
????????????????????????????????????????????????????????????????????????????????
Perform operation? [Y|n]: Y
Erasing?                 [*******************                    ]09:45:31.027 FuEngine             failed to cleanup failed composite action: failed to composite_cleanup using dell_dock: failed to subclass open: no proxy

failed to write-firmware: failed to subclass open: no proxy
Devices with no available firmware updates:
 ? Embedded Controller
xxxx@esmbpm2xxx ~ % ./runfwupdtoolsteps.sh
Loading?                 [************************************** ]
Apple Mac14,5
?
??WD22TB4:
  ?   Device ID:          b3db560e794a8ceb981cf5118b5818ac75d0eafd
  ?   Summary:            High performance dock
  ?   Current version:    01.01.00.07
  ?   Vendor:             Dell Inc. (USB:0x413C)
  ?   Install Duration:   1 minute
  ?   Serial Number:      BYFXYT3/3135888993113304
  ?   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ? USB\VID_413C&PID_B06E&hub&embedded
  ?   Device Flags:       ? Updatable
  ?                       ? Supported on remote server
  ?                       ? Device stages updates
  ?                       ? Device can recover flash failures
  ?                       ? Device is usable for the duration of the update
  ?                       ? Signed Payload
  ?
  ??RTS5413 in Dell dock:
  ?     Device ID:        0bcab2ad4789ecbcca1bf84409a79681c8c700aa
  ?     Summary:          USB 3.1 Generation 1 Hub
  ?     Current version:  01.22
  ?     Vendor:           Dell Inc. (USB:0x413C)
  ?     Install Duration: 14 seconds
  ?     GUIDs:            b27d25f1-019d-5718-b41a-02ddaefe5577 ? USB\VID_413C&PID_B06F
  ?                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ? USB\VID_413C&PID_B06F&hub
  ?     Device Flags:     ? Updatable
  ?                       ? Supported on remote server
  ?                       ? Device stages updates
  ?                       ? Device is usable for the duration of the update
  ?                       ? Signed Payload
  ?                       ? Can tag for emulation
  ?
  ??USB4 controller in Dell dock:
        Device ID:        71413822e87deae707da948bd4b7e537af463c19
        Summary:          USB4 controller
        Current version:  41.81
        Vendor:           Dell Inc. (USB:0x8087, TBT:0x00D4)
        Install Duration: 46 seconds
        GUIDs:            b3f8b518-ebdd-5969-9b44-6b096eff5b9b ? USB\VID_8087&PID_0B40
                          c6e7a14f-f13c-55e5-99de-d59461db1d27 ? USB\VID_8087&PID_0B40&HUB_0000
        Device Flags:     ? Updatable
                          ? Device stages updates
                          ? Device is usable for the duration of the update
                          ? Signed Payload
                          ? Can tag for emulation

Loading?                 [************************************** ]
Loading?                 [************************************** ]
Devices with no available firmware updates:
 ? USB4 controller in Dell dock
Apple Mac14,5
?
??RTS5413 in Dell dock:
? ?   Device ID:          0bcab2ad4789ecbcca1bf84409a79681c8c700aa
? ?   Summary:            USB 3.1 Generation 1 Hub
? ?   Current version:    01.22
? ?   Vendor:             Dell Inc. (USB:0x413C)
? ?   Install Duration:   14 seconds
? ?   GUIDs:              b27d25f1-019d-5718-b41a-02ddaefe5577 ? USB\VID_413C&PID_B06F
? ?                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ? USB\VID_413C&PID_B06F&hub
? ?   Device Flags:       ? Updatable
? ?                       ? Supported on remote server
? ?                       ? Device stages updates
? ?                       ? Device is usable for the duration of the update
? ?                       ? Signed Payload
? ?                       ? Can tag for emulation
? ?
? ??WD19/WD22 USB 3.1 Generation 1 Controller Update:
?       New version:      01.23
?       Remote ID:        lvfs
?       Release ID:       102057
?       Summary:          Firmware update for WD19/WD22 USB 3.1 Generation 1
?       License:          Proprietary
?       Size:             65.5?kB
?       Created:          2024-11-12
?       Urgency:          High
?       Vendor:           Dell
?       Duration:         14 seconds
?       Release Flags:    ? Trusted metadata
?                         ? Is upgrade
?       Description:
?       -Fixed the issue where there is a noise when you use Dell Pro Stereo Headset UC350. This issue occurs when you open Zoom or Sound settings.
?       Checksum:         cf16c3d1c0adda35a41763b4b112bba915a262f396bfe025481fb896dca5be8c
?
??WD22TB4:
  ?   Device ID:          b3db560e794a8ceb981cf5118b5818ac75d0eafd
  ?   Summary:            High performance dock
  ?   Current version:    01.01.00.07
  ?   Vendor:             Dell Inc. (USB:0x413C)
  ?   Install Duration:   1 minute
  ?   Serial Number:      BYFXYT3/3135888993113304
  ?   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ? USB\VID_413C&PID_B06E&hub&embedded
  ?   Device Flags:       ? Updatable
  ?                       ? Supported on remote server
  ?                       ? Device stages updates
  ?                       ? Device can recover flash failures
  ?                       ? Device is usable for the duration of the update
  ?                       ? Signed Payload
  ?
  ??WD19/WD22 EC Embedded Controller Update:
        New version:      01.01.00.10
        Remote ID:        lvfs
        Release ID:       102053
        Summary:          Firmware update for WD19/WD22 EC
        License:          Proprietary
        Size:             131.0?kB
        Created:          2024-11-12
        Urgency:          High
        Vendor:           Dell
        Duration:         1 minute
        Release Flags:    ? Trusted metadata
                          ? Is upgrade
        Description:
        -Fixed the issue where the system automatically shuts down when you plug or unplug the dock to the system.

        -Fixed the issue where the USB device and Preboot Execution Environment (PXE) boot option are not displayed. This issue occurs when you restart or power on the system and press the F12 key to enter the BIOS Setup or Boot Menu.
        Checksum:         cf16c3d1c0adda35a41763b4b112bba915a262f396bfe025481fb896dca5be8c

Loading?                 [************************************** ]
????????????????????????????????????????????????????????????????????????????????
? Upgrade RTS5413 in Dell dock from 01.22 to 01.23?                            ?
????????????????????????????????????????????????????????????????????????????????
? -Fixed the issue where there is a noise when you use Dell Pro Stereo         ?
? Headset UC350. This issue occurs when you open Zoom or Sound settings.       ?
?                                                                              ?
? RTS5413 in Dell dock must remain connected for the duration of the update    ?
? to avoid damage.                                                             ?
????????????????????????????????????????????????????????????????????????????????
Perform operation? [Y|n]: Y
Erasing?                 [*******************                    ]09:45:48.893 FuEngine             failed to cleanup failed composite action: failed to composite_cleanup using dell_dock: failed to subclass open: no proxy

failed to write-firmware: failed to subclass open: no proxy
????????????????????????????????????????????????????????????????????????????????
? Upgrade WD22TB4 from 01.01.00.07 to 01.01.00.10?                             ?
????????????????????????????????????????????????????????????????????????????????
? -Fixed the issue where the system automatically shuts down when you plug or  ?
? unplug the dock to the system.                                               ?
?                                                                              ?
? -Fixed the issue where the USB device and Preboot Execution Environment      ?
? (PXE) boot option are not displayed. This issue occurs when you restart or   ?
? power on the system and press the F12 key to enter the BIOS Setup or Boot    ?
? Menu.                                                                        ?
????????????????????????????????????????????????????????????????????????????????
Perform operation? [Y|n]: Y
Erasing?                 [*******************                    ]09:45:53.176 FuEngine             failed to cleanup failed composite action: failed to composite_cleanup using dell_dock: failed to subclass open: no proxy

failed to write-firmware: failed to subclass open: no proxy
Devices with no available firmware updates:
 ? Embedded Controller
```shell
fwupdmgr get-devices --filter=~internal
```

</details>

**Dock SKU**
Please mention which module is installed in your WD19.

- [ ] WD19 (Single-C)
- [ ] WD19TB (Thunderbolt)
- [ ] WD19DC (Dual-C)
- [ X] WD22TB4

**Peripherals connected to the dock**
Please describe all devices connected to the dock.  Be as specific as possible,
including USB devices, hubs, monitors, and downstream type-C devices.

**Verbose daemon logs**
First enable daemon verbose logs collection.

```shell
fwupdmgr modify-config "VerboseDomains" "*"
```

Then try to reproduce the issue.  Even if it doesn't reproduce, please attach the
daemon verbose logs collected from the system journal.

```shell
journalctl -b -u fwupd.service
```

**Additional questions**

- Operating system and version:
- Have you tried unplugging the dock or any peripherals from your machine?
- Have you tried to power cycle the dock from the AC adapter?
- Is this a regression?

### PR DESCRIPTION
**Pull request by CragW**
Fixes #8368

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

File: plugins/dell-dock/fu-dell-dock-status.c [hunk 1]
```diff
@@ -97,6 +99,29 @@ fu_dell_dock_status_write(FuDevice *device,
...
+			fu_device_add_instance_id(device, DELL_DOCK_DOCK2_INSTANCE_ID);
+		else
+			fu_device_add_instance_id(device, DELL_DOCK_DOCK1_INSTANCE_ID);
+	} else {
+		g_set_error(error,
+			    FWUPD_ERROR,
+			    FWUPD_ERROR_NOT_SUPPORTED,
+			    "unknown supported dock type 0x%x",
+			    self->dock_type);
+	}
```
Comment (hughsie) [inline plugins/dell-dock/fu-dell-dock-status.c:120]: needs a return FALSE here?

File: wd22tb4.zip
Comment (superm1) [inline wd22tb4.zip:1]: Please don't commit binaries.

**Review by superm1 — CHANGES_REQUESTED** [review]
Drop the binary.

**Comment by CragW** [comment]
> Drop the binary.

I think `git add .` apparently not a good idea, fixed.

**Review by superm1 — APPROVED** [review]
