### PR TITLE
Set the firmware contents even when subclassing ->parse()

### LINKED ISSUE #5021: mtd: FuUswidFirmware type fails to install 'no payload set'
**Describe the bug**

While #4294 is resolved and the version is now properly reported, fwupd seems to fail when (re)installing the firmware with:

```
pine64-pinephonepro:/home/dylan# fwupdmgr reinstall 2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
WARNING: This package has not been validated, it may not work properly.
╔══════════════════════════════════════════════════════════════════════════════╗
║ Reinstall Tow-Boot platform firmware to 2021.10-005?                         ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Improvements:                                                                ║
║                                                                              ║
║ • First initial release with fwupd support                                   ║
║                                                                              ║
║ Tow-Boot platform firmware and all connected devices may not be usable       ║
║ while updating.                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]: 
Decompressing…           [                                       ]no payload set

```

When a version is manually patched into fwupd (to workaround the version check) and you supply the CAB file, it gets flashed without any issue. 

Quirk file `mtd.quirk`:

```
pine64-pinephonepro:/home/dylan# cat /usr/share/fwupd/quirks.d/mtd.quirk 
[MTD]
plugin = mtd

[MTD\VENDOR_PINE64&PRODUCT_PinePhone-Pro&NAME_spi1.0]
Name = Tow-Boot platform firmware
FirmwareGType = FuUswidFirmware

```

CAB file metainfo:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2021-2022 Dylan Van Assche <me@dylanvanassche.be> -->
<component type="firmware">
  <id>org.tow-boot.pine64-pinephonePro.firmware</id>
  <name>Pine64 PinePhone Pro</name>
  <name_variant_suffix>Tow-Boot platform firmware</name_variant_suffix>
  <summary>Tow-Boot platform firmware for Pine64 PinePhone Pro</summary>
  <description>
    <p>
      Updating your platform firmware may bring new features, security fixes, and other improvements. Upgrading at your own risk!
    </p>
  </description>
  <categories>
    <category>X-Device</category>
    <category>X-System</category>
  </categories>
  <provides>
    <!-- Match the pine64-pinephonePro Tow-Boot storage -->
    <firmware type="flashed">d18da1b4-b822-537a-a2e9-6a0ff7a821e3</firmware>
  </provides>
  <url type="homepage">https://tow-boot.org/</url>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>MIT</project_license>
  <releases>
    <release urgency="high" version="2021.10-005" date="2022-09-04" install_duration="120">
      <checksum type="sha1" filename="Tow-Boot.uswid.spi.2021.10-005.bin" target="content">2600580f29527d2e028657227035ff7aa935955c</checksum>
      <checksum type="sha256" filename="Tow-Boot.uswid.spi.2021.10-005.bin" target="content">af12adaff278c7afec3b8b7468d77ae4209af95e645e53b491580f5da75067bc</checksum>
      <url type="source">https://github.com/Tow-Boot/Tow-Boot/</url>
      <description>
<p>Improvements:</p>
<ul>
  <li>First initial release with fwupd support</li>
</ul>
      </description>
      <issues>
      </issues>
    </release>
  </releases>
  <!-- Required versions of fwupd, firmware, etc. -->
  <requires>
    <id compare="ge" version="1.7.2">org.freedesktop.fwupd</id>
    <hardware>c7faf1e2-fa9e-5754-bbb2-3cb68b269f8a</hardware>
  </requires>
  <!-- Custom firmware flashing methods and quirks -->
  <custom>
    <value key="LVFS::UpdateProtocol">org.infradead.mtd</value>
  </custom>
  <!-- Search keywords -->
  <keywords>
    <keyword>UEFI</keyword>
    <keyword>platform-firmware</keyword>
    <keyword>tow-boot</keyword>
  </keywords>
</component>
```

CAB file: 
[cab.zip](https://github.com/fwupd/fwupd/files/9537179/cab.zip)

**Steps to Reproduce**

1. Set the firmware type to FuUswidFirmware
2. Try to install a CAB file

**Expected behavior**

Firmware is extracted from the CAB file and flashed

**fwupd version information**
Please provide the version of the daemon and client.

```shell
pine64-pinephonepro:/home/dylan# fwupdmgr --version
runtime   org.freedesktop.fwupd         1.8.5
compile   org.freedesktop.gusb          0.3.10
runtime   org.kernel                    5.17.9
compile   com.hughsie.libjcat           0.1.10
compile   org.freedesktop.fwupd         1.8.5
runtime   org.freedesktop.gusb          0.3.10

```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): apk

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
pine64-pinephonepro:/home/dylan# fwupdmgr get-devices --show-all-devices
WARNING: This package has not been validated, it may not work properly.
PINE64 PinePhone Pro
│
├─QUECTEL Mobile Broadband Module:
│     Device ID:          27730920c2119d128e431bbd20a8f225a2013d3a
│     Summary:            Quectel EG25-G modem
│     Current version:    0.5.9
│     Vendor:             Qualcomm (USB:0x2C7C)
│     Release Branch:     community
│     GUIDs:              db379a33-254f-5140-b37e-d36ae7e5c039
│                         d18f31f1-a3fa-55a2-b4ed-decfbc1e004d ← USB\VID_2C7C&PID_0125&REV_0318&NAME_EG25GGB
│                         1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
│                         587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
│                         22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
│     Device Flags:       • Updatable
│                         • System requires external power source
│   
└─Tow-Boot platform firmware:
      Device ID:          2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
      Summary:            Memory Technology Device
      Current version:    2021.10-005
      Vendor:             DMI:PINE64
      GUIDs:              b50f1204-cdaa-5403-8391-fd85a6022d4b ← MTD\NAME_spi1.0
                          8bcdf5eb-f779-5780-9014-c85c04e73cc1 ← MTD\VENDOR_PINE64&NAME_spi1.0
                          d18da1b4-b822-537a-a2e9-6a0ff7a821e3 ← MTD\VENDOR_PINE64&PRODUCT_PinePhone-Pro&NAME_spi1.0
      Device Flags:       • Internal device
                          • Updatable
                          • Supported on remote server
                          • Needs a reboot after installation
                          • Cryptographic hash verification is available

```

fwupd logs:

```
pine64-pinephonepro:/home/dylan# /usr/libexec/fwupd/fwupd -v
16:27:29:0384 FuDebug              Verbose debugging enabled (on console 1)
16:27:29:0389 FuConfig             trying to load config values from /etc/fwupd/daemon.conf
16:27:29:0390 FuCommon             reading /etc/fwupd/daemon.conf with 2081 bytes
16:27:29:0390 FuConfig             trying to load config values from /var/etc/fwupd/daemon.conf
16:27:29:0390 FuConfig             using autodetected max archive size 18.4 EB
16:27:29:0394 FuRemoteList         loading /usr/share/fwupd/metainfo
16:27:29:0396 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
16:27:29:0396 XbSilo               file: f5f16767-760f-0a57-daa7-1e1932c81ddf, current:f5f16767-760f-0a57-daa7-1e1932c81ddf, cached: (null)
16:27:29:0396 XbSilo               loading silo with file contents
16:27:29:0397 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor-directory.conf
16:27:29:0398 FuRemoteList         loading remote from /etc/fwupd/remotes.d/fwupd-tests.conf
16:27:29:0399 FuRemoteList         skipping invalid file /etc/fwupd/remotes.d/vendor-directory.conf.apk-new
16:27:29:0400 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs-testing.conf
16:27:29:0401 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor.conf
16:27:29:0402 FuRemoteList         skipping invalid file /etc/fwupd/remotes.d/vendor.conf.apk-new
16:27:29:0402 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs.conf
16:27:29:0404 FuRemoteList         ordering lvfs-testing=lvfs+1
16:27:29:0404 FuRemoteList         ignoring unfound remote fwupd
16:27:29:0404 Jcat                 reading /etc/pki/fwupd/LVFS-CA.pem with 1679 bytes
16:27:29:0405 Jcat                 loaded 1 certificates
16:27:29:0405 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
16:27:29:0406 Jcat                 ignoring GPG-KEY-Linux-Foundation-Firmware as not PKCS-7 certificate
16:27:29:0406 Jcat                 reading /etc/pki/fwupd-metadata/LVFS-CA.pem with 1679 bytes
16:27:29:0407 Jcat                 loaded 1 certificates
16:27:29:0407 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
16:27:29:0407 Jcat                 ignoring GPG-KEY-Linux-Foundation-Metadata as not PKCS-7 certificate
16:27:29:0407 Jcat                 reading /var/lib/fwupd/pki/secret.key with 2459 bytes
16:27:29:0407 Jcat                 reading /var/lib/fwupd/pki/client.pem with 1383 bytes
16:27:29:0408 FuEngine             client certificate now exists: nothing to do
16:27:29:0408 FuHistory            trying to open database '/var/lib/fwupd/pending.db'
16:27:29:0410 FuHistory            got schema version of 8
16:27:29:0412 FuPlugin             load(/usr/lib/fwupd-plugins-7/libfu_plugin_fastboot.so)
16:27:29:0433 FuPlugin             load(/usr/lib/fwupd-plugins-7/libfu_plugin_modem_manager.so)
16:27:29:0435 FuIdle               setting timeout to 7200s
16:27:29:0525 FuCommon             reading /proc/self/exe with 330472 bytes
16:27:29:0529 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d
16:27:29:0530 FuQuirks             loading quirks from /var/lib/fwupd/quirks.d
16:27:29:0530 XbSilo               attempting to load /var/cache/fwupd/quirks.xmlb
16:27:29:0530 XbSilo               file: 7d27bfcf-baff-2f4f-b5d6-3c3b6b37344c, current:7d27bfcf-baff-2f4f-b5d6-3c3b6b37344c, cached: (null)
16:27:29:0530 XbSilo               loading silo with file contents
16:27:29:0531 FuQuirks             invalid key names: CcgxDmcTriggerCode,CcgxFlashRowSize,CcgxFlashSize,CcgxImageKind,CorsairDeviceKind,CxaudioChipIdBase,CxaudioPatch1ValidAddr,CxaudioPatch2ValidAddr,DellDockBlobBuildOffset,DellDockBlobMajorOffset,DellDockBlobMinorOffset,DellDockBlobVersionOffset,DellDockBoardMin,DellDockHubVersionLowest,DellDockInstallDurationI2C,DellDockUnlockTarget,DellDockVersionLowest,DfuAltName,DfuForceTimeout,DfuForceVersion,ElantpI2cTargetAddress,ElantpIapPassword,ElantpIcPageCount,GenesysScalerCfiFlashId,GenesysScalerGpioEnableRegister,GenesysScalerGpioOutputRegister,GenesysScalerGpioValue,GenesysUsbhubReadRequest,GenesysUsbhubSwitchRequest,GenesysUsbhubWriteRequest,JabraMagic,LogitechHidppModelId,NordicHidBootloader,ParadeLspconAuxDeviceName,PciBcrAddr,RealtekMstDpAuxName,RealtekMstDrmCardKernelName,Rts54I2cSpeed,Rts54RegisterAddrLen,Rts54TargetAddr,SuperioAutoloadAction,SuperioControlPort,SuperioDataPort,SuperioGType,SuperioId,SuperioPort,SuperioTimeout,SynapticsMstDeviceKind,WacomI2cFlashBaseAddr,WacomI2cFlashBlockSize,WacomI2cFlashSize
16:27:29:0532 FuHwids              loading HwId overrides from /etc/fwupd/daemon.conf
16:27:29:0532 FuHwids              not loading HwId overrides from /var/lib/fwupd/daemon.conf
16:27:29:0532 FuHwids              smbios property Manufacturer=PINE64
16:27:29:0532 FuHwids              smbios property EnclosureKind=3
16:27:29:0533 FuHwids              smbios property Family=PinePhone
16:27:29:0533 FuHwids              smbios property ProductName=PinePhone Pro
16:27:29:0533 FuHwids              ignoring ProductSku: no data available
16:27:29:0533 FuHwids              smbios property BiosVendor=U-Boot
16:27:29:0533 FuHwids              smbios property BiosVersion=2021.10
16:27:29:0533 FuHwids              smbios property BiosMajorRelease=15
16:27:29:0533 FuHwids              smbios property BiosMinorRelease=0a
16:27:29:0533 FuHwids              smbios property FirmwareMajorRelease=ff
16:27:29:0533 FuHwids              smbios property FirmwareMinorRelease=ff
16:27:29:0533 FuHwids              smbios property BaseboardManufacturer=PINE64
16:27:29:0533 FuHwids              smbios property BaseboardProduct=PinePhone Pro
16:27:29:0533 FuHwids              HardwareID-0 is not available, not available as 'ProductSku' unknown
16:27:29:0533 FuHwids              HardwareID-3 is not available, not available as 'ProductSku' unknown
16:27:29:0533 FuHwids              HardwareID-4 is not available, not available as 'ProductSku' unknown
16:27:29:0533 FuHwids              HardwareID-6 is not available, not available as 'ProductSku' unknown
16:27:29:0533 FuHwids              HardwareID-7 is not available, not available as 'ProductSku' unknown
16:27:29:0544 FuContext            added udev subsystem watch of firmware-attributes
16:27:29:0544 FuContext            Error opening directory “/sys/class/firmware-attributes”: No such file or directory
16:27:29:0544 FuEngine             building metadata for remote 'vendor-directory'
16:27:29:0544 FuEngine             building metadata for /usr/share/fwupd/remotes.d/vendor/firmware/Tow-Boot.uswid.spi.2021.10-005.cab
16:27:29:0547 FuCommon             reading /usr/share/fwupd/remotes.d/vendor/firmware/Tow-Boot.uswid.spi.2021.10-005.cab with 1597814 bytes
16:27:29:0547 FuMain               Emitting PropertyChanged('Status'='decompressing')
16:27:29:0577 FuCabinet            failed to verify Tow-Boot.uswid.spi.2021.10-005.metainfo.xml: no JcatItem
16:27:29:0577 FuCabinet            processing file: Tow-Boot.uswid.spi.2021.10-005.metainfo.xml
16:27:29:0578 FuCabinet            processing release: 2021.10-005
16:27:29:0588 FuEngine             ignoring: /usr/share/fwupd/remotes.d/vendor/firmware/README.md
16:27:29:0588 FuEngine             ignoring: Error opening directory “/var/lib/fwupd/local.d”: No such file or directory
16:27:29:0588 FuEngine             ignoring: Error opening directory “/usr/share/fwupd/local.d”: No such file or directory
16:27:29:0588 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
16:27:29:0588 XbSilo               file: 4f2f5b38-2793-e1a3-7a24-e2a16a59bd52, current:4f2f5b38-2793-e1a3-7a24-e2a16a59bd52, cached: (null)
16:27:29:0588 XbSilo               loading silo with file contents
16:27:29:0593 FuEngine             1602 components now in silo
16:27:29:0657 FuPlugin             init(fastboot)
16:27:29:0657 FuPlugin             init(android_boot)
16:27:29:0657 FuContext            added udev subsystem watch of block
16:27:29:0658 FuPlugin             init(logind)
16:27:29:0658 FuPlugin             init(modem_manager)
16:27:29:0658 FuPlugin             init(mtd)
16:27:29:0658 FuContext            added udev subsystem watch of mtd
16:27:29:0658 FuPlugin             init(upower)
16:27:29:0658 FuPlugin             init(intel_usb4)
16:27:29:0669 FuContext            battery threshold now 10
16:27:29:0669 FuMain               Emitting PropertyChanged('Status'='loading')
16:27:29:0669 FuPlugin             startup(logind)
16:27:29:0674 FuPlugin             startup(modem_manager)
16:27:29:0687 FuPlugin             startup(mtd)
16:27:29:0687 FuPlugin             startup(upower)
16:27:29:0703 FuContext            battery state now charging
16:27:29:0703 FuContext            battery level now 32
16:27:29:0703 FuPlugin             coldplug(modem_manager)
16:27:29:0709 FuPluginMm           ModemManager 1.18.10 is available
16:27:29:0709 FuPluginMm           added modem: /org/freedesktop/ModemManager1/Modem/0
16:27:29:0709 FuPluginMm           valid firmware update combination: fastboot
16:27:29:0719 FuDevice             failed on try 1 of 3: failed to read valid response for AT+QSECBOOT="status": ERROR
16:27:32:0724 FuDevice             failed on try 2 of 3: failed to read valid response for AT+QSECBOOT="status": ERROR
16:27:37:0230 FuPluginMm           AT command failed (AT+QSECBOOT="status"): failed after 3 retries: failed to read response for AT+QSECBOOT="status": timeout
16:27:37:0235 FuDevice             failed on try 1 of 3: failed to read valid response for AT+QCFG="secbootstat": ERROR
16:27:40:0239 FuDevice             failed on try 2 of 3: failed to read valid response for AT+QCFG="secbootstat": ERROR
16:27:43:0243 FuPluginMm           AT command failed (AT+QCFG="secbootstat"): failed after 3 retries: failed to read valid response for AT+QCFG="secbootstat": ERROR
16:27:44:0746 FuDevice             failed on try 1 of 3: failed to read response for AT+GETFWBRANCH: timeout
16:27:47:0754 FuPluginMm           Firmware branch reported as 'community'
16:27:47:0754 FuPluginMm           using firmware branch: community
16:27:47:0754 FuDevice             using 27730920c2119d128e431bbd20a8f225a2013d3a for /sys/devices/platform/fe3c0000.usb/usb2/2-1
16:27:47:0754 FuPlugin             emit added from modem_manager: 27730920c2119d128e431bbd20a8f225a2013d3a
16:27:47:0755 FuEngine             modem_manager device does not define payload QUECTEL Mobile Broadband Module [27730920c2119d128e431bbd20a8f225a2013d3a]
16:27:47:0803 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0803 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0807 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0807 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0810 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0810 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0814 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0814 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0817 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0818 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0818 FuDevice             changing verfmt for 27730920c2119d128e431bbd20a8f225a2013d3a: plain->triplet
16:27:47:0819 FuDeviceList         ::added 27730920c2119d128e431bbd20a8f225a2013d3a
16:27:47:0836 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0836 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0838 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0838 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0841 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0841 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0843 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0843 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0845 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:27:47:0845 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:27:47:0869 FuEngine             using plugins: android_boot, fastboot, intel_usb4, logind, modem_manager, mtd, upower
16:27:47:0870 FuProgress           raw timing data was { 0.000, 0.001 } -- steps were set as [ 1 99 ] but should have been [ 31 69 ] at ../src/fu-usb-backend.c:126
16:27:47:0916 FuPlugin             backend_device_added(modem_manager)
16:27:47:0918 FuUsbDevice          USB device 2:3 is /sys/devices/platform/fe3c0000.usb/usb2/2-1
16:27:47:0942 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1: no plugin ata found
16:27:47:0942 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1: no plugin scsi found
16:27:47:0942 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1: no plugin uf2 found
16:27:47:0942 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1: no plugin emmc found
16:27:47:0948 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p1: no plugin ata found
16:27:47:0948 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p1: no plugin scsi found
16:27:47:0948 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p1: no plugin uf2 found
16:27:47:0948 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p1: no plugin emmc found
16:27:47:0957 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p2: no plugin ata found
16:27:47:0957 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p2: no plugin scsi found
16:27:47:0957 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p2: no plugin uf2 found
16:27:47:0957 FuEngine             failed to add device /sys/devices/platform/fe320000.mmc/mmc_host/mmc1/mmc1:aaaa/block/mmcblk1/mmcblk1p2: no plugin emmc found
16:27:47:0964 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0: no plugin ata found
16:27:47:0964 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0: no plugin scsi found
16:27:47:0964 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0: no plugin uf2 found
16:27:47:0964 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0: no plugin emmc found
16:27:47:0969 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0: no plugin ata found
16:27:47:0969 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0: no plugin scsi found
16:27:47:0969 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0: no plugin uf2 found
16:27:47:0969 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0: no plugin emmc found
16:27:47:0974 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1: no plugin ata found
16:27:47:0974 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1: no plugin scsi found
16:27:47:0974 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1: no plugin uf2 found
16:27:47:0974 FuEngine             failed to add device /sys/devices/platform/fe330000.mmc/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1: no plugin emmc found
16:27:47:0983 FuDevice             unknown device overwriting name value: spi1.0->Tow-Boot platform firmware
16:27:47:0983 FuDevice             using 2270d251f7c1dc37a29a2aa720a566aa0fa0ecde for DEVPATH=/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
16:28:03:0919 FuPlugin             emit added from mtd: 2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
16:28:03:0951 FuEngine             requirement 1.7.2 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:03:0951 FuEngine             HWID provided c7faf1e2-fa9e-5754-bbb2-3cb68b269f8a
16:28:03:0953 FuDeviceList         ::added 2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
16:28:03:0962 FuEngine             requirement 1.7.2 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:03:0962 FuEngine             HWID provided c7faf1e2-fa9e-5754-bbb2-3cb68b269f8a
16:28:03:0988 FuMain               Emitting PropertyChanged('Status'='idle')
16:28:03:0997 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:03:0997 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:03:0999 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:03:0999 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0000 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0000 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0002 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0002 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0003 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0003 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0012 FuEngine             requirement 1.7.2 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0012 FuEngine             HWID provided c7faf1e2-fa9e-5754-bbb2-3cb68b269f8a
16:28:04:0013 FuEngine             ignoring 2021.10-005 == 2021.10-005
16:28:04:0022 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0022 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0023 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0023 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0025 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0025 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0026 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0026 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0028 FuEngine             requirement 1.7.6 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0028 FuEngine             failed to set release for component: no HWIDs matched adad873f-33d3-5477-bd5e-0870eca37444
16:28:04:0036 FuEngine             requirement 1.7.2 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:04:0036 FuEngine             HWID provided c7faf1e2-fa9e-5754-bbb2-3cb68b269f8a
16:28:04:0038 FuEngine             writing motd target /var/cache/fwupd/motd.d/85-fwupd

../src/fu-daemon.c:2294 [34687.85ms]:
    ../src/fu-engine.c:7582:load-engine [34675.20ms]:
        ../src/fu-engine.c:5814:plugins-coldplug [18165.50ms]:
            :modem_manager [18165.14ms]
        ../src/fu-engine.c:7527:backend-coldplug [16118.93ms]:
            ../src/fu-engine.c:7490:udev [16053.39ms]:
                ../src/fu-engine.c:7471:add-devices [16048.39ms]:
                    ../src/fu-engine.c:7076:/sys/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0 [16008.97ms]:
                        ../src/fu-engine.c:7041:query-possible-plugins [16006.68ms]:
                            :mtd [16006.62ms]

16:28:04:0074 FuProgress           raw timing data was { 0.000, 0.001 } -- steps were set as [ 1 99 ] but should have been [ 31 69 ] at ../src/fu-usb-backend.c:126
16:28:04:0075 GLib-GIO             Failed to initialize portal (GMemoryMonitorPortal) for gio-memory-monitor: Not using portals
16:28:04:0075 GLib-GIO             _g_io_module_get_default: Found default implementation dbus (GMemoryMonitorDBus) for ‘gio-memory-monitor’
16:28:04:0075 FuMain               Daemon ready for requests (locale C.UTF-8)
16:28:04:0081 FuMain               acquired name: org.freedesktop.fwupd
16:28:05:0440 FuHistory            parsing 2022-09-04 13:36:18
16:28:05:0441 FuEngine             skipping writing HSI attrs to database as unchanged
16:28:05:0448 FuMain               Called SetHints()
16:28:05:0448 FuMain               got hint locale=C.UTF-8
16:28:05:0453 FuMain               Called GetPlugins()
16:28:05:0460 FuMain               Called SetFeatureFlags(511)
16:28:05:0469 FuMain               Called Install(*,9)
16:28:05:0469 FuMain               got option reason
16:28:05:0470 FuMain               got option filename
16:28:05:0470 FuMain               got option allow-reinstall
16:28:05:0477 FuMain               Emitting PropertyChanged('Status'='decompressing')
16:28:05:0533 FuCabinet            failed to verify Tow-Boot.uswid.spi.2021.10-005.metainfo.xml: no JcatItem
16:28:05:0533 FuCabinet            processing file: Tow-Boot.uswid.spi.2021.10-005.metainfo.xml
16:28:05:0535 FuCabinet            processing release: 2021.10-005
16:28:05:0552 FuEngine             requirement 1.7.2 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:05:0552 FuEngine             HWID provided c7faf1e2-fa9e-5754-bbb2-3cb68b269f8a
16:28:05:0552 FuEngine             requirement 1.7.2 ge 1.8.5 -> org.freedesktop.fwupd passed
16:28:05:0552 FuEngine             HWID provided c7faf1e2-fa9e-5754-bbb2-3cb68b269f8a
16:28:05:0552 FuMain               Emitting PropertyChanged('Status'='waiting-for-auth')
16:28:05:0575 FuIdle               inhibiting: update
16:28:05:0575 FuEngine             composite update 1: 2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
16:28:05:0576 FuHistory            remove device Tow-Boot platform firmware [2270d251f7c1dc37a29a2aa720a566aa0fa0ecde]
16:28:05:0595 FuHistory            add device Tow-Boot platform firmware [2270d251f7c1dc37a29a2aa720a566aa0fa0ecde]
16:28:05:0612 FuMain               Emitting PropertyChanged('Status'='device-busy')
16:28:05:0612 FuDeviceList         no replug or re-enumerate required
16:28:05:0613 FuHistory            modifying device Tow-Boot platform firmware [2270d251f7c1dc37a29a2aa720a566aa0fa0ecde]
16:28:05:0635 FuEngine             prepare -> FuMtdDevice:
  DeviceId:             2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
  Name:                 Tow-Boot platform firmware
  Guid:                 b50f1204-cdaa-5403-8391-fd85a6022d4b ← MTD\NAME_spi1.0
  Guid:                 8bcdf5eb-f779-5780-9014-c85c04e73cc1 ← MTD\VENDOR_PINE64&NAME_spi1.0
  Guid:                 d18da1b4-b822-537a-a2e9-6a0ff7a821e3 ← MTD\VENDOR_PINE64&PRODUCT_PinePhone-Pro&NAME_spi1.0
  Summary:              Memory Technology Device
  Plugin:               mtd
  Protocol:             org.infradead.mtd
  Flags:                internal|supported|registered|needs-reboot|can-verify|can-verify-image|updatable-hidden
  VendorId:             DMI:PINE64
  Version:              2021.10-005
  Icon:                 drive-harddisk-solidstate
  Created:              2022-09-09
  Modified:             2022-09-09
  UpdateError:          An update is in progress
  PhysicalId:           DEVPATH=/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  BackendId:            /sys/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  AcquiesceDelay:       2500
  FirmwareGType:        FuUswidFirmware
  FirmwareSizeMax:      16777216
  Order:                0
  PossiblePlugin:       mtd
  InternalFlags:        md-set-signed
  Inhibit:              [update-in-progress] An update is in progress
  EraseSize:            0x1000

16:28:05:0636 FuPlugin             prepare(logind)
16:28:05:0650 FuPluginLogind       opened logind fd 15
16:28:05:0650 FuDeviceList         no replug or re-enumerate required
16:28:05:0650 FuMain               Emitting PropertyChanged('Status'='device-write')
16:28:05:0651 FuMain               Emitting PropertyChanged('Percentage'='1%')
16:28:05:0651 FuDeviceList         no replug or re-enumerate required
16:28:05:0651 FuMain               Emitting PropertyChanged('Status'='device-restart')
16:28:05:0651 FuDeviceList         no replug or re-enumerate required
16:28:05:0652 FuEngine             detach -> FuMtdDevice:
  DeviceId:             2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
  Name:                 Tow-Boot platform firmware
  Guid:                 b50f1204-cdaa-5403-8391-fd85a6022d4b ← MTD\NAME_spi1.0
  Guid:                 8bcdf5eb-f779-5780-9014-c85c04e73cc1 ← MTD\VENDOR_PINE64&NAME_spi1.0
  Guid:                 d18da1b4-b822-537a-a2e9-6a0ff7a821e3 ← MTD\VENDOR_PINE64&PRODUCT_PinePhone-Pro&NAME_spi1.0
  Summary:              Memory Technology Device
  Plugin:               mtd
  Protocol:             org.infradead.mtd
  Flags:                internal|supported|registered|needs-reboot|can-verify|can-verify-image|updatable-hidden
  VendorId:             DMI:PINE64
  Version:              2021.10-005
  Icon:                 drive-harddisk-solidstate
  Created:              2022-09-09
  Modified:             2022-09-09
  UpdateError:          An update is in progress
  PhysicalId:           DEVPATH=/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  BackendId:            /sys/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  AcquiesceDelay:       2500
  FirmwareGType:        FuUswidFirmware
  FirmwareSizeMax:      16777216
  Order:                0
  PossiblePlugin:       mtd
  InternalFlags:        md-set-signed
  Inhibit:              [update-in-progress] An update is in progress
  EraseSize:            0x1000

16:28:05:0652 FuPlugin             detach(mtd)
16:28:05:0652 FuMain               Emitting PropertyChanged('Status'='device-write')
16:28:05:0653 FuMain               Emitting PropertyChanged('Percentage'='2%')
16:28:05:0653 FuDeviceList         no replug or re-enumerate required
16:28:05:0655 FuEngine             update -> FuMtdDevice:
  DeviceId:             2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
  Name:                 Tow-Boot platform firmware
  Guid:                 b50f1204-cdaa-5403-8391-fd85a6022d4b ← MTD\NAME_spi1.0
  Guid:                 8bcdf5eb-f779-5780-9014-c85c04e73cc1 ← MTD\VENDOR_PINE64&NAME_spi1.0
  Guid:                 d18da1b4-b822-537a-a2e9-6a0ff7a821e3 ← MTD\VENDOR_PINE64&PRODUCT_PinePhone-Pro&NAME_spi1.0
  Summary:              Memory Technology Device
  Plugin:               mtd
  Protocol:             org.infradead.mtd
  Flags:                internal|supported|registered|needs-reboot|can-verify|can-verify-image|updatable-hidden
  VendorId:             DMI:PINE64
  Version:              2021.10-005
  Icon:                 drive-harddisk-solidstate
  Created:              2022-09-09
  Modified:             2022-09-09
  UpdateError:          An update is in progress
  PhysicalId:           DEVPATH=/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  BackendId:            /sys/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  AcquiesceDelay:       2500
  FirmwareGType:        FuUswidFirmware
  FirmwareSizeMax:      16777216
  Order:                0
  PossiblePlugin:       mtd
  InternalFlags:        md-set-signed
  Inhibit:              [update-in-progress] An update is in progress
  EraseSize:            0x1000

16:28:05:0655 FuPlugin             superclassed write_firmware(mtd)
16:28:05:0655 FuMain               Emitting PropertyChanged('Status'='decompressing')
16:28:05:0817 FuDevice             installing onto 2270d251f7c1dc37a29a2aa720a566aa0fa0ecde:
<firmware gtype="FuUswidFirmware">
  <flags>has-stored-size</flags>
  <offset>0x1855f0</offset>
  <size>0x107</size>
  <hdrver>0x1</hdrver>
  <firmware gtype="FuCoswidFirmware">
    <id>acbd84ff-9898-4922-8ade-dd4bbe2e40ba</id>
    <version>2021.10-005</version>
    <size>0xf0</size>
    <filename>Tow-Boot.spi.bin</filename>
  </firmware>
</firmware>

16:28:05:0817 FuPlugin             attach(mtd)
16:28:05:0817 FuDeviceList         no replug or re-enumerate required
16:28:05:0818 FuHistory            modifying device Tow-Boot platform firmware [2270d251f7c1dc37a29a2aa720a566aa0fa0ecde]
16:28:05:0838 FuEngine             cleanup -> FuMtdDevice:
  DeviceId:             2270d251f7c1dc37a29a2aa720a566aa0fa0ecde
  Name:                 Tow-Boot platform firmware
  Guid:                 b50f1204-cdaa-5403-8391-fd85a6022d4b ← MTD\NAME_spi1.0
  Guid:                 8bcdf5eb-f779-5780-9014-c85c04e73cc1 ← MTD\VENDOR_PINE64&NAME_spi1.0
  Guid:                 d18da1b4-b822-537a-a2e9-6a0ff7a821e3 ← MTD\VENDOR_PINE64&PRODUCT_PinePhone-Pro&NAME_spi1.0
  Summary:              Memory Technology Device
  Plugin:               mtd
  Protocol:             org.infradead.mtd
  Flags:                internal|updatable|supported|registered|needs-reboot|can-verify|can-verify-image
  VendorId:             DMI:PINE64
  Version:              2021.10-005
  Icon:                 drive-harddisk-solidstate
  Created:              2022-09-09
  Modified:             2022-09-09
  PhysicalId:           DEVPATH=/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  BackendId:            /sys/devices/platform/ff1d0000.spi/spi_master/spi1/spi1.0/mtd/mtd0
  AcquiesceDelay:       2500
  FirmwareGType:        FuUswidFirmware
  FirmwareSizeMax:      16777216
  Order:                0
  PossiblePlugin:       mtd
  InternalFlags:        md-set-signed
  EraseSize:            0x1000

16:28:05:0838 FuPlugin             cleanup(logind)
16:28:05:0838 FuPluginLogind       closed logind fd 15
16:28:05:0838 FuDeviceList         no replug or re-enumerate required
16:28:05:0839 FuHistory            modifying device Tow-Boot platform firmware [2270d251f7c1dc37a29a2aa720a566aa0fa0ecde]
16:28:05:0854 FuHistory            modifying device Tow-Boot platform firmware [2270d251f7c1dc37a29a2aa720a566aa0fa0ecde]
16:28:05:0875 FuIdle               uninhibiting: update
16:28:05:0876 FuMain               Emitting PropertyChanged('Status'='idle')
```

**Additional questions**

- Operating system and version: postmarketOS edge
- Have you tried rebooting? Yes
- Is this a regression? No

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

Fixes #5021

### CODE REVIEW

**Comment by hughsie** [comment]
@DylanVanAssche I'd be interesting if this helps with your mtd issue too.

File: libfwupdplugin/fu-firmware.c [hunk 1]
```diff
@@ -906,6 +906,11 @@ fu_firmware_parse_full(FuFirmware *self,
 	}
 	if (!fu_firmware_check_magic_for_offset(self, fw, &offset, flags, error))
 		return FALSE;
+
+	/* always set by default */
+	fu_firmware_set_bytes(self, fw);
```
Comment (superm1) [inline libfwupdplugin/fu-firmware.c:911]: if you're always setting this, I think you should also move the alignment check to always check it.

Comment (hughsie) [reply libfwupdplugin/fu-firmware.c:911]: I don't think we can, think ihex, srec etc

Comment (superm1) [reply libfwupdplugin/fu-firmware.c:911]: Oh right.

**Review by superm1 — APPROVED** [review]

**Comment by DylanVanAssche** [comment]
@hughsie It does fix my issue! Thanks!
