### PR TITLE
Modem manager branch support

### LINKED ISSUE #4114: Branches are not remembered after switch
**Describe the bug**

Branches are not remembered when using `fwupmgr switch branch $GUID $BRANCH`.
As soon as the switch is complete and the alternative firmware is flashed, the branch seems to be forgotten according to the fwupd logs:

```
17:06:51:0297 FuEngine             ignoring EG25GGBR07A08M2G - 05010820 == EG25GGBR07A08M2G - 05010820
17:06:51:0297 FuEngine             ignoring release PINEPHONE_MODEM_SDK_0.4.10-002 as branch biktorgj-002, and device is (null)
```

I used `switch-branch` to move to the `biktorgj-002` branch, but that doesn't seem to be picked up.
The firmware version `PINEPHONE_MODEM_SDK_0.4.10-002` is different from (and higher than) the one reported by the modem `EG25GGBR07A08M2G - 05010820`, so an update should be advertised.

Is there a way to see on which branch a device currently is? I don't see it with `get-devices`.

**Steps to Reproduce**
1. Switch to a different branch
2. Finish the upgrade
3. Put a newer firmware in the repos
4. No updates are advertised

**Expected behavior**

The newer firmware is detected, processed and shown as an update.

**fwupd version information**
f6833f96c309e74da7f537bc0fa11d7ad52dfb3a

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): git

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
Pine64 PinePhone (1.2)
│
├─DA4032:
│     Device ID:          0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
│     Current version:    0x3034313430363139
│     Vendor:             EMMC:0x000045
│     Serial Number:      0x67ecec14
│     GUIDs:              8c6f96d4-f406-53fa-84ca-a367cd368dfc ← EMMC\DA4032
│                         add792f2-7053-5638-80e7-20987fd16769 ← EMMC\0069&0256
│                         5500994c-1b73-52b4-acf4-bb574b6f3029 ← EMMC\0069&0256&DA4032
│     Device Flags:       • Internal device
│                         • Updatable
│   
└─QUECTEL Mobile Broadband Module:
      Device ID:          976c4a39e87f61e6940ea6a8d39c583cfa99615f
      Summary:            Quectel EG25-G modem
      Current version:    EG25GGBR07A08M2G - 05010820
      Vendor:             QUALCOMM INCORPORATED (USB:0x2C7C)
      GUIDs:              db379a33-254f-5140-b37e-d36ae7e5c039
                          c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
                          1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
                          587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
                          22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
      Device Flags:       • Updatable
                          • System requires external power source
                          • Supported on remote server
                          • Device supports switching to a different branch of firmware

```

**Additional questions**

- Operating system and version: postmarketOS edge, PinePhone
- Have you tried rebooting? Yes
- Is this a regression? Yes, it should work as it is supported for firmware like coreboot: https://fwupd.org/lvfs/devices/com.starlabs.L3.coreboot.flashrom

### PR DESCRIPTION
**Pull request by DylanVanAssche**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [x] Feature
- [ ] Documentation

# Changes

- Add support for setting the firmware branch in `modem-manager` plugin.
- Read firmware branch using a custom AT command from the modem.
- Configure the quirk for the Quectel EG25-G modem to use `AT+GETFWBRANCH` as custom AT command to get the firmware branch

**Alternative firmware running 0.5.1 on branch `FOSS-002`**:
```
└─QUECTEL Mobile Broadband Module:
      Device ID:          976c4a39e87f61e6940ea6a8d39c583cfa99615f
      Summary:            Quectel EG25-G modem
      Current version:    0.5.1
      Vendor:             QUALCOMM INCORPORATED (USB:0x2C7C)
      Release Branch:     FOSS-002
      GUIDs:              db379a33-254f-5140-b37e-d36ae7e5c039
                          1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
                          587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
                          22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
      Device Flags:       • Updatable
                          • System requires external power source
                          • Supported on remote server
                          • Device supports switching to a different branch of firmware
```

If the AT command fails or is not implemented by the current running firmware, the error generated by it is unset and we consider running the default branch = official Quectel firmware.

# Involved issues

Fixes #4114 

# Environment

- Pine64 PinePhone, Quectel EG25-G
- postmarketOS edge, musl
- fwupd main

### CODE REVIEW

File: plugins/modem-manager/fu-mm-device.c [hunk 1]
```diff
@@ -663,6 +666,32 @@ fu_mm_device_at_cmd(FuMmDevice *self, const gchar *cmd, gboolean has_response, G
...
+	/* set firmware branch if returned */
+	if (self->branch_at != NULL && g_strcmp0(cmd, self->branch_at) == 0) {
+		/*
+		 * example AT+GETFWBRANCH response:
+		 *
+		 * \r\nFOSS-002 \r\n\r\nOK\r\n
+		 *
+		 * remove \r\n, and OK to get branch name
+		 */
+		gchar **parts = g_strsplit(buf, "\r\n", -1);
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:679]: this needs to be `g_auto(GStrv)` to avoid leaking.

File: plugins/modem-manager/fu-mm-device.c [hunk 2]
```diff
@@ -663,6 +666,32 @@ fu_mm_device_at_cmd(FuMmDevice *self, const gchar *cmd, gboolean has_response, G
...
+
+		for (int j = 0; parts[j] != NULL; j++) {
+			/* Ignore empty strings, and OK responses */
+			if (g_strcmp0(parts[j], "") != 0 && g_strcmp0(parts[j], "OK") != 0) {
+				g_autofree gchar *branch = g_strdup(parts[j]);
+
+				/* Set branch */
+				fu_device_set_branch(FU_DEVICE(self), branch);
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:687]: can't you just use `parts[j]` directly?

File: plugins/modem-manager/fu-mm-device.c [hunk 3]
```diff
@@ -1432,6 +1461,23 @@ fu_mm_device_write_firmware(FuDevice *device,
 	return FALSE;
 }
 
+static gboolean
+fu_mm_device_set_quirk_kv(FuDevice *device, const gchar *key, const gchar *value, GError **error)
+{
+	FuMmDevice *self = FU_MM_DEVICE(device);
+	guint64 tmp = 0;
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1468]: unused?

File: plugins/modem-manager/fu-mm-device.c [hunk 4]
```diff
@@ -1504,6 +1550,32 @@ fu_mm_device_attach(FuDevice *device, FuProgress *progress, GError **error)
...
+	locker = fu_device_locker_new_full(device,
+					   (FuDeviceLockerFunc)fu_mm_device_io_open,
+					   (FuDeviceLockerFunc)fu_mm_device_io_close,
+					   error);
+	/*
+	 * firmware branch AT command may fail if not implemented,
+	 * clear error if not supported
+	 */
+	if (self->branch_at != NULL && !fu_mm_device_at_cmd(self, self->branch_at, TRUE, error))
+		g_clear_error(error);
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1569]: rather than doing this, please use `g_autoptr(GError) error_local = NULL` in this function scope. Then you can g_debug() the error_local->message on failure.

File: plugins/modem-manager/fu-mm-device.c [hunk 5]
```diff
@@ -1518,6 +1590,7 @@ fu_mm_device_set_progress(FuDevice *self, FuProgress *progress)
 static void
 fu_mm_device_init(FuMmDevice *self)
 {
+	self->branch_at = NULL;
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1593]: no need to do this, the entire struct is memset to 0x0

File: plugins/modem-manager/fu-mm-device.c [hunk 6]
```diff
@@ -59,6 +59,7 @@ struct _FuMmDevice {
 	 */
 	MMModemFirmwareUpdateMethod update_methods;
 	gchar *detach_fastboot_at;
+	gchar *branch_at;
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:62]: unused?

Comment (DylanVanAssche) [reply plugins/modem-manager/fu-mm-device.c:62]: Used to store the quirk value.
This is then used as AT command to get the branch.

Comment (hughsie) [reply plugins/modem-manager/fu-mm-device.c:62]: I misread the function, sorry for the noise!

Comment (hughsie) [reply plugins/modem-manager/fu-mm-device.c:62]: Ohh, then don't you need to g_free it in finalize?

Comment (DylanVanAssche) [reply plugins/modem-manager/fu-mm-device.c:62]: Oh yes, good catch!

File: plugins/modem-manager/fu-mm-device.c [hunk 7]
```diff
@@ -1504,6 +1546,34 @@ fu_mm_device_attach(FuDevice *device, FuProgress *progress, GError **error)
...
+					   (FuDeviceLockerFunc)fu_mm_device_io_open,
+					   (FuDeviceLockerFunc)fu_mm_device_io_close,
+					   error);
+	/*
+	 * firmware branch AT command may fail if not implemented,
+	 * clear error if not supported
+	 */
+	if (self->branch_at != NULL &&
+	    !fu_mm_device_at_cmd(self, self->branch_at, TRUE, error_branch))
+		g_debug("Unable to get firmware branch: %s", error_branch->message);
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1567]: i think a nested `if` would be much clearer here.

File: plugins/modem-manager/fu-mm-device.c [hunk 8]
```diff
@@ -1504,6 +1546,34 @@ fu_mm_device_attach(FuDevice *device, FuProgress *progress, GError **error)
...
+
+	if (fu_device_get_branch(device) != NULL)
+		g_debug("Found firmware branch: %s", fu_device_get_branch(device));
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1570]: lowercase first word i think

File: plugins/modem-manager/fu-mm-device.c [hunk 9]
```diff
@@ -1504,6 +1546,34 @@ fu_mm_device_attach(FuDevice *device, FuProgress *progress, GError **error)
...
+	else
+		g_debug("Running default firmware branch");
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1572]: do we really need this?

Comment (DylanVanAssche) [reply plugins/modem-manager/fu-mm-device.c:1572]: I added to make it clear from the logs which branch is used.
So whatever modem you have, you can always find the branch in the logs.

Comment (hughsie) [reply plugins/modem-manager/fu-mm-device.c:1572]: maybe just `g_debug("using firmware branch: %s", fu_device_get_branch(device));` for both cases?

Comment (DylanVanAssche) [reply plugins/modem-manager/fu-mm-device.c:1572]: That would be `null` then for the default branch which doesn't read great in the logs.

Comment (hughsie) [reply plugins/modem-manager/fu-mm-device.c:1572]: okay, fair enough; just make the first word lower case then LGTM.

**Review by hughsie — APPROVED** [review]

File: plugins/modem-manager/fu-mm-device.c [hunk 10]
```diff
@@ -1504,6 +1546,35 @@ fu_mm_device_attach(FuDevice *device, FuProgress *progress, GError **error)
...
+	/* Create IO channel to send AT commands to the modem */
+	locker = fu_device_locker_new_full(device,
+					   (FuDeviceLockerFunc)fu_mm_device_io_open,
+					   (FuDeviceLockerFunc)fu_mm_device_io_close,
+					   &error);
+	/*
+	 * firmware branch AT command may fail if not implemented,
+	 * clear error if not supported
+	 */
+	if (self->branch_at != NULL) {
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1565]: tiny nit: error_branch could be created here

Comment (DylanVanAssche) [reply plugins/modem-manager/fu-mm-device.c:1565]: Ah don't we declare all variables at the beginning of a function?

Comment (hughsie) [reply plugins/modem-manager/fu-mm-device.c:1565]: in general we try to err on creating them as "local" as possible, but sticking them at the top of whatever block.

File: plugins/modem-manager/fu-mm-device.c [hunk 11]
```diff
@@ -1504,6 +1546,35 @@ fu_mm_device_attach(FuDevice *device, FuProgress *progress, GError **error)
...
+{
+	FuMmDevice *self = FU_MM_DEVICE(device);
+	g_autoptr(FuDeviceLocker) locker = NULL;
+	g_autoptr(GError) error_branch = NULL;
+
+	/* Create IO channel to send AT commands to the modem */
+	locker = fu_device_locker_new_full(device,
+					   (FuDeviceLockerFunc)fu_mm_device_io_open,
+					   (FuDeviceLockerFunc)fu_mm_device_io_close,
+					   &error);
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1560]: you need to either check locker for NULL here (and return FALSE) or use something like error_locker and then only do the at_cmd when locker != NULL. Also, no & on the error.
