### PR TITLE
modem-manager: add Quectel EG25-G modem support

### LINKED ISSUE #3968: modem-manager: Quectel EG25-G fastboot updates fail due to USB disconnections
**Describe the bug**

Quectel EG25-G modem can be upgraded through `fastboot` which is possible with `fwupd`, but as soon as the actual upgrade starts, the bulk transfer of the firmware files fail [1] with `USB error on device 18d1:d00d : No such device (it may have been disconnected) [-4]`. The modem seems to disconnect during the probing and the writing of the firmware over fastboot.

I added a quirk as [done for other modems](https://github.com/fwupd/fwupd/blob/main/plugins/modem-manager/modem-manager.quirk#L2-L5) to handle the handover of the original GUID and the fastboot GUID (see [2]).
This particular modem does not reply `OK` like the [plugin expects](https://github.com/fwupd/fwupd/blob/main/plugins/modem-manager/fu-mm-device.c#L628-L652) so I patched `fwupd` to ignore this as this modem directly enters fastboot mode (see [3]). I plan to rework this as a `modem-manager` plugin quirk.

In [4] I included the verbose log of `fwupd` together with the udev events that are happening which shows the disconnection in between.

[1] https://github.com/fwupd/fwupd/blob/main/plugins/fastboot/fu-fastboot-device.c#L106-L117
[2] Quirk:
```
# Quectel EG25-G
[USB\VID_2C7C&PID_0125]
Summary = Quectel EG25-G modem
CounterpartGuid = USB\VID_18D1&PID_D00D

# Quectel EG25-G in fastboot mode
[USB\VID_18D1&PID_D00D]
Summary = Quectel EG25-G modem (fastboot)
CounterpartGuid = USB\VID_2C7C&PID_0125
```
[3] Temporary patch:
```
--- a/plugins/modem-manager/fu-mm-device.c
+++ b/plugins/modem-manager/fu-mm-device.c
@@ -625,6 +625,12 @@ fu_mm_device_at_cmd(FuMmDevice *self, const gchar *cmd, GError **error)
 					  1500,
 					  FU_IO_CHANNEL_FLAG_SINGLE_SHOT,
 					  error);
+	/* 
+	 * HACK: always assume that booting into fastboot works
+	 * Quectel EG25-G modem does not send a response, it just EOFed
+	 */
+	return TRUE;
+
 	if (at_res == NULL) {
 		g_prefix_error(error, "failed to read response for %s: ", cmd);
 		return FALSE;
```
[4] [log-fwupd-no-such-device.txt](https://github.com/fwupd/fwupd/files/7506860/log-fwupd-no-such-device.txt)

**Steps to Reproduce**
1. Run `fwupdmgr install <CAB file>` on a device with a Quectel EG25-G modem installed such as a PinePhone
2. `fwupd` unpacks the CAB file, switches the modem into fastboot mode, inhibits ModemManager
3. `fwupd` fails to upgrade the firmware because it cannot initiate a bulk transfer: `USB error on device 18d1:d00d : No such device (it may have been disconnected) [-4]`

**Expected behavior**

USB bulk transfer with the firmware starts and the flashing process completes.

**fwupd version information**

```shell
pine64-pinephone:~$ fwupdmgr --version
client version:	1.7.1
compile-time dependency versions
	gusb:	0.3.8
daemon version:	1.7.1
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): Alpine Linux's apk

**fwupd device information**

```shell
Pine64 PinePhone (1.2)
│
├─DA4032:
│     Device ID:          0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
│     Current version:    0x3034313430363139
│     Vendor:             EMMC:0x000045
│     GUIDs:              8c6f96d4-f406-53fa-84ca-a367cd368dfc
│                         add792f2-7053-5638-80e7-20987fd16769
│                         5500994c-1b73-52b4-acf4-bb574b6f3029
│     Device Flags:       • Internal device
│                         • Updatable
│   
└─QUECTEL Mobile Broadband Module:
      Device ID:          976c4a39e87f61e6940ea6a8d39c583cfa99615f
      Summary:            Mobile broadband device
      Current version:    EG25GGBR07A08M2G - 05010820
      Vendor:             QUALCOMM INCORPORATED (USB:0x2C7C)
      GUIDs:              c33a4560-8681-55b6-bbb6-85258f2de149
                          1a2996cb-f86e-5583-a464-e1b96e1c6ae9
                          587bf468-6859-5522-93a7-6cce552a0aa3
                          22ae45db-f68e-5c55-9c02-4557dca238ec
      Device Flags:       • Updatable

```

**Additional questions**

- Operating system and version: postmarketOS edge (Alpine Linux edge)
- Have you tried rebooting? Yes
- Is this a regression? No

### PR DESCRIPTION
**Pull request by DylanVanAssche**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

# Description

The Quectel EG25-G modem is used in the [Pine64 PinePhone](https://pine64.org/pinephone) and [PinePhone Pro](https://pine64.org/pinephonepro) .
By default it ships with an old firmware version which can be upgraded to newer versions from Quectel or a more open firmware developed at https://github.com/Biktorgj/pinephone_modem_sdk.
The current `fwupd` version sees the Quectel EG25-G through the `modem-manager` plugin as upgradable using the `fastboot` plugin. However, the Quectel EG25-G fastboot bootloader is picky when you interact with it:

- Blocksize must be `16384` bytes, not a byte more or less. If you still try another size, the next chunk the `fastboot` plugin writes to the modem fails which reboots the bootloader. I discovered this by analyzing the USB traffic of the same payload (once with `fwupd` and once with the original fastboot binary) with Wireshark.
- Writing and reading data cannot happen at `fwupd`'s rate otherwise the fastboot bootloader crashes and reboot, the original fastboot binary seems to have some delay between writes/reads. If you enable the debug prints of the `fastboot` plugin, this is also 'fixed', but I properly fixed it by introducing a new quirk.
- The modem shows up under an entirely different USB vendor and device ID which causes `fwupd` to not see it. Adding the necessary quirks in `modem-manager` fixes it (like done for all other modems there).

# Changes

- Add GUIDs for the Quectel EG25-G modem in fastboot to `modem-manager` plugin's quirks
- Introduce a new quirk `ModemManagerAtHasResponse` to ignore the responses when entering fastboot mode, default: expects a response.
- Add this no response quirk for the Quectel EG25-G modem
- Introduce a delay operations quirk in the `fastboot` plugin to sleep after a read or write operation, default: 0 us.
- Add this delay operations quirk tor the Quectel EG25-G modem

# Test environment

- Pine64 PinePhone with a Quectel EG25-G modem
- Alpine Linux / postmarketOS edge
- musl

# Disclaimer for distros

*These patches are not ready to be shipped to end-users, I kindly ask you to not ship them to any users, even when they are bleeding edge channels of your distro. At all times, I'm not responsible for complains about bricked modems!*

# Related issues

Fixes #3968

### CODE REVIEW

**Comment by DylanVanAssche** [comment]
@superm1 I found a fix for #3968 :)
However, I cannot convince `fwupd` of reading my new quirk `ModemManagerDetachAtFastbootHasResponse` in `modem-manager.quirk`. If I hardcode the value I need, the code path works, so it is just a matter of reading the quirk correctly. I added some debug prints and the `fu_mm_device_set_quirk_kv` function is not called at all. Am I missing something?

File: plugins/modem-manager/fu-mm-device.c [hunk 1]
```diff
@@ -1494,6 +1500,31 @@ fu_mm_device_set_progress(FuDevice *self, FuProgress *progress)
...
+			  const gchar *key,
+			  const gchar *value,
+			  GError **error)
+{
+	FuMmDevice *self = FU_MM_DEVICE(device);
+
+	/* load from quirks */
+	if (g_strcmp0(key, "ModemManagerDetachAtFastbootHasResponse") == 0) {
+		if (g_strcmp0(value, "true") == 0)
+			self->detach_at_fastboot_has_response = TRUE;
```
Comment (hughsie) [inline plugins/modem-manager/fu-mm-device.c:1514]: This should be a flag, e.g. `fu_device_register_private_flag()` and then `Flags = detach-at-fastboot-has-response`

File: plugins/fastboot/fu-fastboot-device.c [hunk 2]
```diff
@@ -111,6 +113,10 @@ fu_fastboot_device_write(FuDevice *device, const guint8 *buf, gsize buflen, GErr
 					 FASTBOOT_TRANSACTION_TIMEOUT,
 					 NULL,
 					 error);
+
+	/* give device some time to handle action */
+	g_usleep(self->operation_delay);
```
Comment (hughsie) [inline plugins/fastboot/fu-fastboot-device.c:118]: I'm guessing `g_usleep(0)` is a NOP, right?

File: plugins/fastboot/README.md [hunk 3]
```diff
@@ -47,6 +47,12 @@ Block size to use for transfers.
 
 Since: 1.2.2
 
+### FastbootOperationDelay
+
+Time in us to delay after a read or write operation.
```
Comment (hughsie) [inline plugins/fastboot/README.md:52]: I think using ms rather than us is probably more typical for this kind of thing.

File: plugins/fastboot/README.md [hunk 4]
```diff
@@ -47,6 +47,12 @@ Block size to use for transfers.
...
+
+Since: 1.7.3
```
Comment (hughsie) [inline plugins/fastboot/README.md:54]: 1.7.4, sorry -- I just did a release.

File: plugins/modem-manager/fu-mm-device.c (hunk 1 above)
Comment (DylanVanAssche) [reply plugins/modem-manager/fu-mm-device.c]: I tried that (updated the commits), but for some reason these flags are also not processed...
I checked other plugins and I don't see what I'm missing to be honest.

Any advice?

File: plugins/fastboot/fu-fastboot-device.c [hunk 5]
```diff
@@ -19,11 +19,13 @@
 #define FASTBOOT_EP_IN			   0x81
 #define FASTBOOT_EP_OUT			   0x01
 #define FASTBOOT_CMD_BUFSZ		   64 /* bytes */
+#define FASTBOOT_US_TO_MS		   1000
```
Comment (superm1) [inline plugins/fastboot/fu-fastboot-device.c:22]: any reason can't use the glib macros?  I guess they go to seconds, do you really need ms?

File: plugins/modem-manager/fu-mm-device.c (hunk 1 above)
Comment (superm1) [reply plugins/modem-manager/fu-mm-device.c]: It should be coming from `fu_device_set_quirk_kv`->`fu_device_set_custom_flags`->`fu_device_set_custom_flag`->`fu_device_private_flag_item_find_by_str`

Two ways to debug it:
1. Share verbose fwupdtool output, we can see if it's listed there.
2. Set a breakpoint in `fu_device_set_custom_flags` and run fwupdtool get-devices `--plugins=fastboot --plugins-modem-manager` (hopefully I got that right) and walk through it.

**Comment by superm1** [comment]
### Thanks for your commit
The fwupd project has had a style change starting with fwupd 1.6.x.  The style is summarized in https://github.com/fwupd/fwupd/blob/main/CONTRIBUTING.md and it appears your current pull request is inconsistent with the new style.

**Clang Format**
Fortunately we have added a `.clang-format` and various helper scripts to help you fix your pull request.  Follow these steps to configure the environment and fix your code.
1. Run `./contrib/setup` to set up [pre-commit](https://pre-commit.com/) locally.  This will help ensure that you have all the build dependencies necessary and automatically reformat code in the future.
2. Run `./contrib/reformat-code.py main` to reformat all code that has changed in your local branch relative to `main`
3. Run `git commit add .; git commit --amend` or use `git rebase -i` to amend your commit(s).
 
**Pre-commit overview**
The pre-commit rules are available at https://github.com/fwupd/fwupd/blob/main/.pre-commit-config.yaml and will check all languages and text for style.  After you have run `./contrib/setup` any future commits will check the diff relative to all of these rules.

File: plugins/fastboot/fu-fastboot-device.c (hunk 5 above)
Comment (DylanVanAssche) [reply plugins/fastboot/fu-fastboot-device.c:22]: GLib macros go from microseconds to seconds only...
Milliseconds seems like a good compromise regarding precision and readability.

Comment (superm1) [reply plugins/fastboot/fu-fastboot-device.c:22]: Got it, thanks.

File: plugins/modem-manager/fu-mm-device.c (hunk 1 above)
Comment (DylanVanAssche) [reply plugins/modem-manager/fu-mm-device.c]: Ah this shows up: `18:28:34:0551 FuDevice             no registered custom flag detach-at-fastboot-has-response on FuUsbDevice`

**Full log**

```
pine64-pinephone:/home/dylan# fwupdtool --verbose get-devices
18:28:33:0886 FuDebug              Verbose debugging enabled (on console 1)
18:28:33:0888 FuMain               locked /run/lock/fwupdtool
18:28:33:0889 FuConfig             loading config values from /etc/fwupd/daemon.conf
18:28:33:0889 FuConfig             using autodetected max archive size 18.4 EB
18:28:33:0891 GLib-GIO             _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
18:28:33:0893 FuRemoteList         loading /usr/share/fwupd/metainfo
18:28:33:0894 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
18:28:33:0894 XbSilo               file: 8a8e3c95-b816-9f6c-1ff6-543d49ad5e0a, current:8a8e3c95-b816-9f6c-1ff6-543d49ad5e0a, cached: (null)
18:28:33:0894 XbSilo               loading silo with file contents
18:28:33:0895 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor.conf
18:28:33:0896 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs.conf
18:28:33:0897 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs-testing.conf
18:28:33:0899 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor-directory.conf
18:28:33:0899 FuRemoteList         loading remote from /etc/fwupd/remotes.d/fwupd-tests.conf
18:28:33:0901 FuRemoteList         ignoring unfound remote fwupd
18:28:33:0901 FuRemoteList         ordering lvfs-testing=lvfs+1
18:28:33:0901 Jcat                 ignoring GPG-KEY-Linux-Foundation-Firmware as not PKCS-7 certificate
18:28:33:0901 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
18:28:33:0901 Jcat                 trying to load certificate from /etc/pki/fwupd/LVFS-CA.pem
18:28:33:0901 Jcat                 reading /etc/pki/fwupd/LVFS-CA.pem with 1679 bytes
18:28:33:0903 Jcat                 loaded 1 certificates
18:28:33:0905 Jcat                 ignoring GPG-KEY-Linux-Foundation-Metadata as not PKCS-7 certificate
18:28:33:0906 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
18:28:33:0906 Jcat                 trying to load certificate from /etc/pki/fwupd-metadata/LVFS-CA.pem
18:28:33:0907 Jcat                 reading /etc/pki/fwupd-metadata/LVFS-CA.pem with 1679 bytes
18:28:33:0908 Jcat                 loaded 1 certificates
18:28:33:0908 Jcat                 reading /var/lib/fwupd/pki/secret.key with 2459 bytes
18:28:33:0908 Jcat                 reading /var/lib/fwupd/pki/client.pem with 1383 bytes
18:28:33:0908 FuEngine             client certificate now exists: nothing to do
18:28:33:0908 FuHistory            trying to open database '/var/lib/fwupd/pending.db'
18:28:33:0911 FuHistory            got schema version of 7
18:28:33:0912 FuHwids              loading HwId overrides from /etc/fwupd/daemon.conf
18:28:33:0912 FuHwids              not loading HwId overrides from /var/lib/fwupd/daemon.conf
18:28:33:0913 FuHwids              ignoring Manufacturer: no data available
18:28:33:0916 FuHwids              smbios property EnclosureKind=8
18:28:33:0918 FuHwids              ignoring Family: offset bigger than size 6
18:28:33:0918 FuHwids              smbios property ProductName=Pine64 PinePhone (1.2)
18:28:33:0918 FuHwids              ignoring ProductSku: offset bigger than size 6
18:28:33:0918 FuHwids              ignoring BiosVendor: offset bigger than size 0
18:28:33:0918 FuHwids              ignoring BiosVersion: offset bigger than size 0
18:28:33:0919 FuHwids              ignoring BiosMajorRelease: offset bigger than size 0
18:28:33:0919 FuHwids              ignoring BiosMinorRelease: offset bigger than size 0
18:28:33:0919 FuHwids              ignoring FirmwareMajorRelease: offset bigger than size 0
18:28:33:0919 FuHwids              ignoring FirmwareMinorRelease: offset bigger than size 0
18:28:33:0919 FuHwids              ignoring BaseboardManufacturer: offset bigger than size 0
18:28:33:0919 FuHwids              ignoring BaseboardProduct: offset bigger than size 0
18:28:33:0919 FuHwids              HardwareID-0 is not available, not available as 'Manufacturer' unknown
18:28:33:0919 FuHwids              HardwareID-1 is not available, not available as 'Manufacturer' unknown
18:28:33:0919 FuHwids              HardwareID-2 is not available, not available as 'Manufacturer' unknown
18:28:33:0919 FuHwids              HardwareID-3 is not available, not available as 'Manufacturer' unknown
18:28:33:0919 FuHwids              HardwareID-4 is not available, not available as 'Manufacturer' unknown
18:28:33:0919 FuHwids              HardwareID-5 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-6 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-7 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-8 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-9 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-10 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-11 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-12 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-13 is not available, not available as 'Manufacturer' unknown
18:28:33:0920 FuHwids              HardwareID-14 is not available, not available as 'Manufacturer' unknown
18:28:33:0921 FuEngine             building metadata for remote 'vendor-directory'
18:28:33:0922 FuEngine             building metadata for /usr/share/fwupd/remotes.d/vendor/firmware/EG25GGBR07A08M2G_01.002.01.002-recovery.cab
18:28:33:0961 FuCommon             reading /usr/share/fwupd/remotes.d/vendor/firmware/EG25GGBR07A08M2G_01.002.01.002-recovery.cab with 11644303 bytes
18:28:33:0961 FuEngine             Emitting PropertyChanged('Status'='decompressing')
Decompressing…           [-                                      ]18:28:34:0131 FuCabinet            failed to verify EG25GGBR07A08M2G_01.002.01.002.metainfo.xml: no JcatItem
18:28:34:0131 FuCabinet            processing file: EG25GGBR07A08M2G_01.002.01.002.metainfo.xml
18:28:34:0131 XbSilo               compiling 6040e4d37707646f5576d1e9c4be58c2400ebe39:filename=EG25GGBR07A08M2G_01.002.01.002-recovery\EG25GGBR07A08M2G_01.002.01.002.metainfo.xml:prefix=components…
18:28:34:0133 FuCabinet            processing release: EG25GGBR07A08M2G_01.002.01.002
18:28:34:0187 FuEngine             Emitting PropertyChanged('Status'='idle')
Decompressing…           [***************************************]
18:28:34:0196 FuEngine             ignoring: /usr/share/fwupd/remotes.d/vendor/firmware/README.md
18:28:34:0196 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
18:28:34:0196 XbSilo               file: e311220e-9159-3ce8-2a44-4ee8cb9cee68, current:e311220e-9159-3ce8-2a44-4ee8cb9cee68, cached: (null)
18:28:34:0197 XbSilo               loading silo with file contents
18:28:34:0203 FuEngine             1204 components now in silo
18:28:34:0246 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_modem_manager.so)
18:28:34:0248 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_parade_lspcon.so)
18:28:34:0248 FuContext            added udev subsystem watch of i2c
18:28:34:0249 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nvme.so)
18:28:34:0249 FuContext            added udev subsystem watch of nvme
18:28:34:0250 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ebitdo.so)
18:28:34:0252 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_capsule.so)
18:28:34:0253 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_cxaudio.so)
18:28:34:0254 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_fresco_pd.so)
18:28:34:0255 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_pk.so)
18:28:34:0256 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_colorhug.so)
18:28:34:0257 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ata.so)
18:28:34:0257 FuContext            added udev subsystem watch of block
18:28:34:0258 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_elanfp.so)
18:28:34:0260 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logitech_hidpp.so)
18:28:34:0260 FuContext            added udev subsystem watch of hidraw
18:28:34:0261 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_analogix.so)
18:28:34:0262 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_jabra.so)
18:28:34:0264 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dfu.so)
18:28:34:0265 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ccgx.so)
18:28:34:0266 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_lockdown.so)
18:28:34:0266 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_optionrom.so)
18:28:34:0267 FuContext            added udev subsystem watch of pci
18:28:34:0269 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logitech_bulkcontroller.so)
18:28:34:0270 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nordic_hid.so)
18:28:34:0271 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_elantp.so)
18:28:34:0271 FuContext            added udev subsystem watch of i2c-dev
18:28:34:0272 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_rts54hid.so)
18:28:34:0273 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_powerd.so)
18:28:34:0274 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_rts54hub.so)
18:28:34:0275 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_iommu.so)
18:28:34:0275 FuContext            added udev subsystem watch of iommu
18:28:34:0276 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dfu_csr.so)
18:28:34:0277 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_emmc.so)
18:28:34:0278 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_realtek_mst.so)
18:28:34:0279 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_cpu.so)
18:28:34:0280 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_hailuck.so)
18:28:34:0281 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_tainted.so)
18:28:34:0289 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_tpm.so)
18:28:34:0289 FuContext            added udev subsystem watch of tpm
18:28:34:0291 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_bcm57xx.so)
18:28:34:0292 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_fastboot.so)
18:28:34:0293 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dell_dock.so)
18:28:34:0295 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ep963x.so)
18:28:34:0296 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_steelseries.so)
18:28:34:0297 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_cape.so)
18:28:34:0298 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_acpi_phat.so)
18:28:34:0299 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_mst.so)
18:28:34:0299 FuContext            added udev subsystem watch of drm
18:28:34:0300 FuContext            added udev subsystem watch of drm_dp_aux_dev
18:28:34:0301 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_recovery.so)
18:28:34:0302 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nitrokey.so)
18:28:34:0303 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_wacom_raw.so)
18:28:34:0304 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_vli.so)
18:28:34:0305 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pci_bcr.so)
18:28:34:0306 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_goodixmoc.so)
18:28:34:0308 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_superio.so)
18:28:34:0309 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_thelio_io.so)
18:28:34:0309 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_system76_launch.so)
18:28:34:0310 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pci_mei.so)
18:28:34:0312 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_prometheus.so)
18:28:34:0313 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_thunderbolt.so)
18:28:34:0313 FuContext            added udev subsystem watch of thunderbolt
18:28:34:0314 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pixart_rf.so)
18:28:34:0316 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_upower.so)
18:28:34:0316 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_swap.so)
18:28:34:0319 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_rmi.so)
18:28:34:0319 FuContext            added udev subsystem watch of serio
18:28:34:0320 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logind.so)
18:28:34:0321 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_wacom_usb.so)
18:28:34:0322 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_dbx.so)
18:28:34:0324 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_cros_ec.so)
18:28:34:0325 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_mtd.so)
18:28:34:0325 FuContext            added udev subsystem watch of mtd
18:28:34:0325 FuPluginList         uefi_capsule [0] to be ordered after upower [0] so promoting to [1]
18:28:34:0325 FuPluginList         uefi_recovery [0] to be ordered after uefi_capsule [1] so promoting to [2]
18:28:34:0325 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
18:28:34:0325 FuPluginList         bcm57xx [0] better than optionrom [0] so bumping to [1]
18:28:34:0325 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
18:28:34:0325 FuPluginList         dell_dock [0] better than synaptics_mst [0] so bumping to [1]
18:28:34:0325 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
18:28:34:0361 XbSilo               attempting to load /var/cache/fwupd/quirks.xmlb
18:28:34:0362 XbSilo               file: a16ffa3d-ab7f-6bfa-0dbb-e84ce0d1b6f0, current:a16ffa3d-ab7f-6bfa-0dbb-e84ce0d1b6f0, cached: (null)
18:28:34:0362 XbSilo               loading silo with file contents
18:28:34:0368 FuContext            battery threshold now 10
18:28:34:0368 FuEngine             Emitting PropertyChanged('Status'='loading')
Loading…                 [ -                                     ]18:28:34:0369 FuPlugin             startup(bios)
18:28:34:0370 FuPlugin             startup(lenovo_thinklmi)
18:28:34:0370 FuEngine             disabling plugin because: failed to startup using lenovo_thinklmi: thinklmi not available
18:28:34:0370 FuPlugin             startup(linux_lockdown)
18:28:34:0371 FuPlugin             startup(linux_swap)
18:28:34:0371 FuPlugin             startup(linux_tainted)
18:28:34:0372 FuPlugin             startup(logind)
18:28:34:0382 FuPlugin             startup(logitech_hidpp)
18:28:34:0382 FuPlugin             startup(modem_manager)
18:28:34:0399 FuPlugin             startup(mtd)
18:28:34:0399 FuPlugin             startup(powerd)
18:28:34:0405 FuEngine             disabling plugin because: failed to startup using powerd: no service that owns the name for org.chromium.PowerManager
18:28:34:0405 FuPlugin             startup(thunderbolt)
18:28:34:0405 FuPlugin             startup(tpm)
18:28:34:0406 FuPlugin             startup(upower)
18:28:34:0414 FuContext            battery state now charging
18:28:34:0414 FuContext            battery level now 99
18:28:34:0415 FuPlugin             startup(uefi_capsule)
18:28:34:0415 FuEngine             disabling plugin because: failed to startup using uefi_capsule: offset bigger than size 0
18:28:34:0415 FuPlugin             startup(uefi_recovery)
18:28:34:0415 FuEngine             disabling plugin because: failed to startup using uefi_recovery: kernel efivars support missing: /sys/firmware/efi/efivars
18:28:34:0415 FuPlugin             coldplug(acpi_phat)
18:28:34:0416 FuEngine             disabling plugin because: failed to coldplug using acpi_phat: Failed to open file “/sys/firmware/acpi/tables/PHAT”: No such file or directory
18:28:34:0416 FuPlugin             coldplug(amt)
18:28:34:0416 FuEngine             disabling plugin because: failed to coldplug using amt: Unable to find a ME interface
18:28:34:0416 FuPlugin             coldplug(bios)
18:28:34:0416 FuPlugin             coldplug(cpu)
18:28:34:0417 FuEngine             disabling plugin because: failed to coldplug using cpu: no <cpuid.h> support
18:28:34:0417 FuPlugin             coldplug(modem_manager)
18:28:34:0423 FuPluginMm           ModemManager 1.18.2 is available
18:28:34:0424 FuPluginMm           valid firmware update combination: fastboot
18:28:34:0426 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

18:28:34:0426 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

18:28:34:0426 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318 ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

18:28:34:0427 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318 ⚠
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125 ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

18:28:34:0427 FuDevice             using 976c4a39e87f61e6940ea6a8d39c583cfa99615f for /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
18:28:34:0427 FuPlugin             emit added from modem_manager: 976c4a39e87f61e6940ea6a8d39c583cfa99615f
18:28:34:0479 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
18:28:34:0482 FuPlugin             fu_plugin_device_registered(dell_dock)
18:28:34:0483 FuPlugin             fu_plugin_device_registered(pci_bcr)
18:28:34:0483 FuPlugin             fu_plugin_device_registered(thunderbolt)
18:28:34:0483 FuPlugin             fu_plugin_device_registered(tpm)
18:28:34:0483 FuPlugin             fu_plugin_device_registered(uefi_pk)
18:28:34:0483 FuDeviceList         ::added 976c4a39e87f61e6940ea6a8d39c583cfa99615f
18:28:34:0483 FuMain               ADDED:
FuMmDevice:
  DeviceId:             976c4a39e87f61e6940ea6a8d39c583cfa99615f
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
  Summary:              Mobile broadband device
  Plugin:               modem_manager
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  VendorId:             USB:0x2C7C
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  Created:              2021-12-13
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

18:28:34:0525 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
18:28:34:0527 FuPlugin             coldplug(superio)
18:28:34:0528 FuPlugin             coldplug(tpm)
18:28:34:0528 FuPluginTpm          failed to load eventlog: Failed to open file “/sys/kernel/security/tpm0/binary_bios_measurements”: No such file or directory
18:28:34:0528 FuPlugin             coldplug(uefi_dbx)
18:28:34:0528 FuDevice             using 230c8b18-8d9b-53ec-838b-6cfc0383493a for main-system-firmware
18:28:34:0529 FuEngine             disabling plugin because: failed to coldplug using uefi_dbx: Error opening file /sys/firmware/efi/efivars/KEK-8be4df61-93ca-11d2-aa0d-00e098032b8c: No such file or directory
18:28:34:0529 FuPlugin             coldplug(uefi_pk)
18:28:34:0529 FuEngine             disabling plugin because: failed to coldplug using uefi_pk: Error opening file /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c: No such file or directory
18:28:34:0529 FuEngine             using plugins: acpi_dmar, acpi_facp, analogix, ata, bcm57xx, bios, ccgx, colorhug, cros_ec, dell_dock, dfu, dfu_csr, ebitdo, elanfp, elantp, emmc, ep963x, fastboot, fresco_pd, goodixmoc, hailuck, iommu, jabra, linux_lockdown, linux_sleep, linux_swap, linux_tainted, logind, logitech_bulkcontroller, logitech_hidpp, modem_manager, mtd, nitrokey, nordic_hid, nvme, optionrom, parade_lspcon, pci_bcr, pci_mei, pixart_rf, realtek_mst, rts54hid, rts54hub, steelseries, superio, synaptics_cape, synaptics_cxaudio, synaptics_mst, synaptics_prometheus, synaptics_rmi, system76_launch, thelio_io, thunderbolt, tpm, upower, vli, wacom_raw, wacom_usb
18:28:34:0551 FuDevice             no registered custom flag detach-at-fastboot-has-response on FuUsbDevice
18:28:34:0748 FuEngine             failed to add device /sys/devices/platform/soc/1c0f000.mmc/mmc_host/mmc0/mmc0:1234/block/mmcblk0: failed get ffu_capable for (null)
18:28:34:0772 FuDevice             using 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7 for DEVPATH=/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001
18:28:34:0777 FuPlugin             emit added from emmc: 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
18:28:34:0809 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
18:28:34:0810 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
18:28:34:0811 FuPlugin             fu_plugin_device_registered(dell_dock)
18:28:34:0811 FuPlugin             fu_plugin_device_registered(pci_bcr)
18:28:34:0811 FuPlugin             fu_plugin_device_registered(thunderbolt)
18:28:34:0811 FuPlugin             fu_plugin_device_registered(tpm)
18:28:34:0811 FuDeviceList         ::added 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
18:28:34:0812 FuMain               ADDED:
FuEmmcDevice:
  DeviceId:             0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
  Name:                 DA4032
  Guid:                 8c6f96d4-f406-53fa-84ca-a367cd368dfc ← EMMC\DA4032
  Guid:                 add792f2-7053-5638-80e7-20987fd16769 ← EMMC\0069&0256
  Guid:                 5500994c-1b73-52b4-acf4-bb574b6f3029 ← EMMC\0069&0256&DA4032
  Serial:               0xb2161c15
  Plugin:               emmc
  Protocol:             org.jedec.mmc
  Flags:                internal|updatable|registered
  VendorId:             EMMC:0x000045
  Version:              0x3034313430363139
  VersionFormat:        number
  Icon:                 media-memory
  Created:              2021-12-13
  PhysicalId:           DEVPATH=/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001
  BackendId:            /sys/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001/block/mmcblk2
  PossiblePlugin:       ata
  PossiblePlugin:       emmc
  InternalFlags:        is-open
  SysfsPath:            /sys/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001/block/mmcblk2
  Subsystem:            block
  DeviceFile:           /dev/mmcblk2
  SectorSize:           512

18:28:34:0813 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
18:28:34:0813 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
18:28:34:0923 FuEngine             Emitting PropertyChanged('Status'='idle')
Loading…                 [***************************************]
18:28:34:0925 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
18:28:34:0925 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
18:28:34:0967 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
18:28:34:0970 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
18:28:34:0970 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
18:28:35:0012 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
18:28:35:0014 FuEngine             writing motd target /var/cache/fwupd/motd.d/85-fwupd
WARNING: UEFI capsule updates not available or enabled in firmware setup
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
WARNING: This package has not been validated, it may not work properly.
18:28:35:0016 FuMain               FuEmmcDevice:
  DeviceId:             0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
  Name:                 DA4032
  Guid:                 8c6f96d4-f406-53fa-84ca-a367cd368dfc ← EMMC\DA4032
  Guid:                 add792f2-7053-5638-80e7-20987fd16769 ← EMMC\0069&0256
  Guid:                 5500994c-1b73-52b4-acf4-bb574b6f3029 ← EMMC\0069&0256&DA4032
  Serial:               0xb2161c15
  Plugin:               emmc
  Protocol:             org.jedec.mmc
  Flags:                internal|updatable|registered
  VendorId:             EMMC:0x000045
  Version:              0x3034313430363139
  VersionFormat:        number
  Icon:                 media-memory
  Created:              2021-12-13

18:28:35:0016 FuMain               FuMmDevice:
  DeviceId:             976c4a39e87f61e6940ea6a8d39c583cfa99615f
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
  Summary:              Mobile broadband device
  Plugin:               modem_manager
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  VendorId:             USB:0x2C7C
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  Created:              2021-12-13

18:28:35:0023 FuPlugin             destroy(synaptics_mst)
18:28:35:0023 FuPlugin             destroy(logind)
18:28:35:0024 FuPlugin             destroy(pci_mei)
18:28:35:0024 FuPlugin             destroy(upower)
18:28:35:0025 FuPlugin             destroy(modem_manager)
18:28:35:0028 FuPlugin             destroy(linux_lockdown)
18:28:35:0028 FuPlugin             destroy(linux_swap)
18:28:35:0029 FuPlugin             destroy(powerd)
18:28:35:0030 FuPlugin             destroy(tpm)
18:28:35:0031 FuPlugin             destroy(linux_tainted)
18:28:35:0032 FuPlugin             destroy(uefi_capsule)
```

**Comment by hughsie** [comment]
> FuDevice no registered custom flag detach-at-fastboot-has-response on FuUsbDevice

I think that's a false positive; we should probably work out how to suppress that for pre-incorporated GTypes.

**Comment by superm1** [comment]
> > FuDevice no registered custom flag detach-at-fastboot-has-response on FuUsbDevice
> 
> I think that's a false positive; we should probably work out how to suppress that for pre-incorporated GTypes.

No, I think it's indicative of where the failure actually is.  That message comes up when nothing was found with `fu_device_private_flag_item_find_by_str`

**Comment by hughsie** [comment]
> No, I think it's indicative of where the failure actually is

Ahh! fu_device_incorporate() probably needs to copy across the private flags too. I can have a look at this after kids bedtime.

**Comment by DylanVanAssche** [comment]
> > No, I think it's indicative of where the failure actually is
> 
> Ahh! fu_device_incorporate() probably needs to copy across the private flags too. I can have a look at this after kids bedtime.

Oh so this might be a regression in fwupd's plugin API?

**Comment by superm1** [comment]
> > > No, I think it's indicative of where the failure actually is
> > 
> > 
> > Ahh! fu_device_incorporate() probably needs to copy across the private flags too. I can have a look at this after kids bedtime.
> 
> Oh so this might be a regression in fwupd's plugin API?

See if https://github.com/fwupd/fwupd/pull/4077 helps

**Comment by hughsie** [comment]
Alternate proposal in https://github.com/fwupd/fwupd/pull/4078

**Comment by DylanVanAssche** [comment]
@superm1 I tried the patch but I still have it:

```
19:43:39:0427 FuDebug              Verbose debugging enabled (on console 1)
19:43:39:0430 FuMain               locked /run/lock/fwupdtool
19:43:39:0435 FuConfig             loading config values from /etc/fwupd/daemon.conf
19:43:39:0435 FuConfig             using autodetected max archive size 18.4 EB
19:43:39:0437 GLib-GIO             _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
19:43:39:0439 FuRemoteList         loading /usr/share/fwupd/metainfo
19:43:39:0440 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
19:43:39:0444 XbSilo               file: 0dc0011e-afb2-ae98-f56a-b3cff732ab4b, current:0dc0011e-afb2-ae98-f56a-b3cff732ab4b, cached: (null)
19:43:39:0444 XbSilo               loading silo with file contents
19:43:39:0445 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor.conf
19:43:39:0445 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs.conf
19:43:39:0447 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs-testing.conf
19:43:39:0448 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor-directory.conf
19:43:39:0448 FuRemoteList         skipping invalid file /etc/fwupd/remotes.d/vendor-directory.conf.apk-new
19:43:39:0449 FuRemoteList         loading remote from /etc/fwupd/remotes.d/fwupd-tests.conf
19:43:39:0450 FuRemoteList         ignoring unfound remote fwupd
19:43:39:0450 FuRemoteList         ordering lvfs-testing=lvfs+1
19:43:39:0450 Jcat                 ignoring GPG-KEY-Linux-Foundation-Firmware as not PKCS-7 certificate
19:43:39:0450 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
19:43:39:0450 Jcat                 trying to load certificate from /etc/pki/fwupd/LVFS-CA.pem
19:43:39:0450 Jcat                 reading /etc/pki/fwupd/LVFS-CA.pem with 1679 bytes
19:43:39:0454 Jcat                 loaded 1 certificates
19:43:39:0454 Jcat                 ignoring GPG-KEY-Linux-Foundation-Metadata as not PKCS-7 certificate
19:43:39:0454 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
19:43:39:0454 Jcat                 trying to load certificate from /etc/pki/fwupd-metadata/LVFS-CA.pem
19:43:39:0455 Jcat                 reading /etc/pki/fwupd-metadata/LVFS-CA.pem with 1679 bytes
19:43:39:0455 Jcat                 loaded 1 certificates
19:43:39:0456 Jcat                 reading /var/lib/fwupd/pki/secret.key with 2459 bytes
19:43:39:0456 Jcat                 reading /var/lib/fwupd/pki/client.pem with 1383 bytes
19:43:39:0456 FuEngine             client certificate now exists: nothing to do
19:43:39:0456 FuHistory            trying to open database '/var/lib/fwupd/pending.db'
19:43:39:0458 FuHistory            got schema version of 7
19:43:39:0459 FuHwids              loading HwId overrides from /etc/fwupd/daemon.conf
19:43:39:0460 FuHwids              not loading HwId overrides from /var/lib/fwupd/daemon.conf
19:43:39:0460 FuHwids              ignoring Manufacturer: no data available
19:43:39:0460 FuHwids              smbios property EnclosureKind=8
19:43:39:0460 FuHwids              ignoring Family: offset bigger than size 6
19:43:39:0461 FuHwids              smbios property ProductName=Pine64 PinePhone (1.2)
19:43:39:0461 FuHwids              ignoring ProductSku: offset bigger than size 6
19:43:39:0461 FuHwids              ignoring BiosVendor: offset bigger than size 0
19:43:39:0461 FuHwids              ignoring BiosVersion: offset bigger than size 0
19:43:39:0461 FuHwids              ignoring BiosMajorRelease: offset bigger than size 0
19:43:39:0465 FuHwids              ignoring BiosMinorRelease: offset bigger than size 0
19:43:39:0466 FuHwids              ignoring FirmwareMajorRelease: offset bigger than size 0
19:43:39:0466 FuHwids              ignoring FirmwareMinorRelease: offset bigger than size 0
19:43:39:0466 FuHwids              ignoring BaseboardManufacturer: offset bigger than size 0
19:43:39:0466 FuHwids              ignoring BaseboardProduct: offset bigger than size 0
19:43:39:0466 FuHwids              HardwareID-0 is not available, not available as 'Manufacturer' unknown
19:43:39:0466 FuHwids              HardwareID-1 is not available, not available as 'Manufacturer' unknown
19:43:39:0466 FuHwids              HardwareID-2 is not available, not available as 'Manufacturer' unknown
19:43:39:0466 FuHwids              HardwareID-3 is not available, not available as 'Manufacturer' unknown
19:43:39:0466 FuHwids              HardwareID-4 is not available, not available as 'Manufacturer' unknown
19:43:39:0466 FuHwids              HardwareID-5 is not available, not available as 'Manufacturer' unknown
19:43:39:0466 FuHwids              HardwareID-6 is not available, not available as 'Manufacturer' unknown
19:43:39:0466 FuHwids              HardwareID-7 is not available, not available as 'Manufacturer' unknown
19:43:39:0467 FuHwids              HardwareID-8 is not available, not available as 'Manufacturer' unknown
19:43:39:0467 FuHwids              HardwareID-9 is not available, not available as 'Manufacturer' unknown
19:43:39:0467 FuHwids              HardwareID-10 is not available, not available as 'Manufacturer' unknown
19:43:39:0467 FuHwids              HardwareID-11 is not available, not available as 'Manufacturer' unknown
19:43:39:0467 FuHwids              HardwareID-12 is not available, not available as 'Manufacturer' unknown
19:43:39:0467 FuHwids              HardwareID-13 is not available, not available as 'Manufacturer' unknown
19:43:39:0467 FuHwids              HardwareID-14 is not available, not available as 'Manufacturer' unknown
19:43:39:0468 FuEngine             building metadata for remote 'vendor-directory'
19:43:39:0468 FuEngine             building metadata for /usr/share/fwupd/remotes.d/vendor/firmware/EG25GGBR07A08M2G_01.002.01.002-recovery.cab
19:43:39:0494 FuCommon             reading /usr/share/fwupd/remotes.d/vendor/firmware/EG25GGBR07A08M2G_01.002.01.002-recovery.cab with 11644303 bytes
19:43:39:0495 FuEngine             Emitting PropertyChanged('Status'='decompressing')
19:43:39:0663 FuCabinet            failed to verify EG25GGBR07A08M2G_01.002.01.002.metainfo.xml: no JcatItem
19:43:39:0663 FuCabinet            processing file: EG25GGBR07A08M2G_01.002.01.002.metainfo.xml
19:43:39:0664 XbSilo               compiling 6040e4d37707646f5576d1e9c4be58c2400ebe39:filename=EG25GGBR07A08M2G_01.002.01.002-recovery\EG25GGBR07A08M2G_01.002.01.002.metainfo.xml:prefix=components…
19:43:39:0666 FuCabinet            processing release: EG25GGBR07A08M2G_01.002.01.002
19:43:39:0719 FuEngine             Emitting PropertyChanged('Status'='idle')
19:43:39:0728 FuEngine             ignoring: /usr/share/fwupd/remotes.d/vendor/firmware/README.md
19:43:39:0728 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
19:43:39:0728 XbSilo               file: e311220e-9159-3ce8-2a44-4ee8cb9cee68, current:e311220e-9159-3ce8-2a44-4ee8cb9cee68, cached: (null)
19:43:39:0728 XbSilo               loading silo with file contents
19:43:39:0735 FuEngine             1204 components now in silo
19:43:39:0778 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_modem_manager.so)
19:43:39:0779 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_parade_lspcon.so)
19:43:39:0780 FuContext            added udev subsystem watch of i2c
19:43:39:0780 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nvme.so)
19:43:39:0781 FuContext            added udev subsystem watch of nvme
19:43:39:0782 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ebitdo.so)
19:43:39:0784 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_capsule.so)
19:43:39:0785 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_cxaudio.so)
19:43:39:0786 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_fresco_pd.so)
19:43:39:0787 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_pk.so)
19:43:39:0788 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_colorhug.so)
19:43:39:0789 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ata.so)
19:43:39:0789 FuContext            added udev subsystem watch of block
19:43:39:0790 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_elanfp.so)
19:43:39:0792 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logitech_hidpp.so)
19:43:39:0792 FuContext            added udev subsystem watch of hidraw
19:43:39:0793 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_analogix.so)
19:43:39:0794 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_jabra.so)
19:43:39:0796 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dfu.so)
19:43:39:0797 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ccgx.so)
19:43:39:0798 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_lockdown.so)
19:43:39:0798 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_optionrom.so)
19:43:39:0798 FuContext            added udev subsystem watch of pci
19:43:39:0801 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logitech_bulkcontroller.so)
19:43:39:0802 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nordic_hid.so)
19:43:39:0803 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_elantp.so)
19:43:39:0804 FuContext            added udev subsystem watch of i2c-dev
19:43:39:0804 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_rts54hid.so)
19:43:39:0805 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_powerd.so)
19:43:39:0806 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_rts54hub.so)
19:43:39:0807 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_iommu.so)
19:43:39:0807 FuContext            added udev subsystem watch of iommu
19:43:39:0808 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dfu_csr.so)
19:43:39:0809 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_emmc.so)
19:43:39:0810 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_realtek_mst.so)
19:43:39:0811 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_cpu.so)
19:43:39:0812 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_hailuck.so)
19:43:39:0813 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_tainted.so)
19:43:39:0821 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_tpm.so)
19:43:39:0821 FuContext            added udev subsystem watch of tpm
19:43:39:0823 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_bcm57xx.so)
19:43:39:0824 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_fastboot.so)
19:43:39:0826 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dell_dock.so)
19:43:39:0827 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ep963x.so)
19:43:39:0828 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_steelseries.so)
19:43:39:0829 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_cape.so)
19:43:39:0830 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_acpi_phat.so)
19:43:39:0831 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_mst.so)
19:43:39:0832 FuContext            added udev subsystem watch of drm
19:43:39:0832 FuContext            added udev subsystem watch of drm_dp_aux_dev
19:43:39:0833 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_recovery.so)
19:43:39:0834 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nitrokey.so)
19:43:39:0835 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_wacom_raw.so)
19:43:39:0837 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_vli.so)
19:43:39:0838 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pci_bcr.so)
19:43:39:0839 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_goodixmoc.so)
19:43:39:0840 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_superio.so)
19:43:39:0841 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_thelio_io.so)
19:43:39:0842 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_system76_launch.so)
19:43:39:0844 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pci_mei.so)
19:43:39:0845 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_prometheus.so)
19:43:39:0846 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_thunderbolt.so)
19:43:39:0846 FuContext            added udev subsystem watch of thunderbolt
19:43:39:0848 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pixart_rf.so)
19:43:39:0849 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_upower.so)
19:43:39:0850 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_swap.so)
19:43:39:0852 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_rmi.so)
19:43:39:0852 FuContext            added udev subsystem watch of serio
19:43:39:0853 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logind.so)
19:43:39:0855 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_wacom_usb.so)
19:43:39:0856 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_dbx.so)
19:43:39:0857 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_cros_ec.so)
19:43:39:0858 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_mtd.so)
19:43:39:0858 FuContext            added udev subsystem watch of mtd
19:43:39:0859 FuPluginList         uefi_capsule [0] to be ordered after upower [0] so promoting to [1]
19:43:39:0859 FuPluginList         uefi_recovery [0] to be ordered after uefi_capsule [1] so promoting to [2]
19:43:39:0859 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
19:43:39:0859 FuPluginList         bcm57xx [0] better than optionrom [0] so bumping to [1]
19:43:39:0859 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
19:43:39:0859 FuPluginList         dell_dock [0] better than synaptics_mst [0] so bumping to [1]
19:43:39:0859 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
19:43:39:0895 XbSilo               attempting to load /var/cache/fwupd/quirks.xmlb
19:43:39:0896 XbSilo               file: b88866a3-6f1f-11e7-3920-d0a1894a702a, current:b88866a3-6f1f-11e7-3920-d0a1894a702a, cached: (null)
19:43:39:0896 XbSilo               loading silo with file contents
19:43:39:0902 FuContext            battery threshold now 10
19:43:39:0902 FuEngine             Emitting PropertyChanged('Status'='loading')
19:43:39:0902 FuPlugin             startup(bios)
19:43:39:0903 FuPlugin             startup(lenovo_thinklmi)
19:43:39:0903 FuEngine             disabling plugin because: failed to startup using lenovo_thinklmi: thinklmi not available
19:43:39:0903 FuPlugin             startup(linux_lockdown)
19:43:39:0904 FuPlugin             startup(linux_swap)
19:43:39:0904 FuPlugin             startup(linux_tainted)
19:43:39:0904 FuPlugin             startup(logind)
19:43:39:0915 FuPlugin             startup(logitech_hidpp)
19:43:39:0915 FuPlugin             startup(modem_manager)
19:43:39:0932 FuPlugin             startup(mtd)
19:43:39:0932 FuPlugin             startup(powerd)
19:43:39:0937 FuEngine             disabling plugin because: failed to startup using powerd: no service that owns the name for org.chromium.PowerManager
19:43:39:0938 FuPlugin             startup(thunderbolt)
19:43:39:0938 FuPlugin             startup(tpm)
19:43:39:0938 FuPlugin             startup(upower)
19:43:39:0947 FuContext            battery state now discharging
19:43:39:0947 FuContext            battery level now 98
19:43:39:0948 FuPlugin             startup(uefi_capsule)
19:43:39:0948 FuEngine             disabling plugin because: failed to startup using uefi_capsule: offset bigger than size 0
19:43:39:0948 FuPlugin             startup(uefi_recovery)
19:43:39:0948 FuEngine             disabling plugin because: failed to startup using uefi_recovery: kernel efivars support missing: /sys/firmware/efi/efivars
19:43:39:0948 FuPlugin             coldplug(acpi_phat)
19:43:39:0948 FuEngine             disabling plugin because: failed to coldplug using acpi_phat: Failed to open file “/sys/firmware/acpi/tables/PHAT”: No such file or directory
19:43:39:0949 FuPlugin             coldplug(amt)
19:43:39:0949 FuEngine             disabling plugin because: failed to coldplug using amt: Unable to find a ME interface
19:43:39:0949 FuPlugin             coldplug(bios)
19:43:39:0949 FuPlugin             coldplug(cpu)
19:43:39:0950 FuEngine             disabling plugin because: failed to coldplug using cpu: no <cpuid.h> support
19:43:39:0950 FuPlugin             coldplug(modem_manager)
19:43:39:0956 FuPluginMm           ModemManager 1.18.2 is available
19:43:39:0956 FuPluginMm           valid firmware update combination: fastboot
19:43:39:0959 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

19:43:39:0959 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

19:43:39:0959 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318 ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

19:43:39:0959 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318 ⚠
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125 ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

19:43:39:0960 FuDevice             using 976c4a39e87f61e6940ea6a8d39c583cfa99615f for /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
19:43:39:0960 FuPlugin             emit added from modem_manager: 976c4a39e87f61e6940ea6a8d39c583cfa99615f
19:43:40:0011 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:43:40:0015 FuPlugin             fu_plugin_device_registered(dell_dock)
19:43:40:0015 FuPlugin             fu_plugin_device_registered(pci_bcr)
19:43:40:0015 FuPlugin             fu_plugin_device_registered(thunderbolt)
19:43:40:0015 FuPlugin             fu_plugin_device_registered(tpm)
19:43:40:0015 FuPlugin             fu_plugin_device_registered(uefi_pk)
19:43:40:0015 FuDeviceList         ::added 976c4a39e87f61e6940ea6a8d39c583cfa99615f
19:43:40:0016 FuMain               ADDED:
FuMmDevice:
  DeviceId:             976c4a39e87f61e6940ea6a8d39c583cfa99615f
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
  Summary:              Mobile broadband device
  Plugin:               modem_manager
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  VendorId:             USB:0x2C7C
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  Created:              2021-12-13
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

19:43:40:0057 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:43:40:0059 FuPlugin             coldplug(superio)
19:43:40:0060 FuPlugin             coldplug(tpm)
19:43:40:0060 FuPluginTpm          failed to load eventlog: Failed to open file “/sys/kernel/security/tpm0/binary_bios_measurements”: No such file or directory
19:43:40:0060 FuPlugin             coldplug(uefi_dbx)
19:43:40:0060 FuDevice             using 230c8b18-8d9b-53ec-838b-6cfc0383493a for main-system-firmware
19:43:40:0061 FuEngine             disabling plugin because: failed to coldplug using uefi_dbx: Error opening file /sys/firmware/efi/efivars/KEK-8be4df61-93ca-11d2-aa0d-00e098032b8c: No such file or directory
19:43:40:0061 FuPlugin             coldplug(uefi_pk)
19:43:40:0061 FuEngine             disabling plugin because: failed to coldplug using uefi_pk: Error opening file /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c: No such file or directory
19:43:40:0061 FuEngine             using plugins: acpi_dmar, acpi_facp, analogix, ata, bcm57xx, bios, ccgx, colorhug, cros_ec, dell_dock, dfu, dfu_csr, ebitdo, elanfp, elantp, emmc, ep963x, fastboot, fresco_pd, goodixmoc, hailuck, iommu, jabra, linux_lockdown, linux_sleep, linux_swap, linux_tainted, logind, logitech_bulkcontroller, logitech_hidpp, modem_manager, mtd, nitrokey, nordic_hid, nvme, optionrom, parade_lspcon, pci_bcr, pci_mei, pixart_rf, realtek_mst, rts54hid, rts54hub, steelseries, superio, synaptics_cape, synaptics_cxaudio, synaptics_mst, synaptics_prometheus, synaptics_rmi, system76_launch, thelio_io, thunderbolt, tpm, upower, vli, wacom_raw, wacom_usb
19:43:40:0084 FuDevice             no registered custom flag detach-at-fastboot-has-response on FuUsbDevice
19:43:40:0280 FuEngine             failed to add device /sys/devices/platform/soc/1c0f000.mmc/mmc_host/mmc0/mmc0:1234/block/mmcblk0: failed get ffu_capable for (null)
19:43:40:0304 FuDevice             using 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7 for DEVPATH=/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001
19:43:40:0309 FuPlugin             emit added from emmc: 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
19:43:40:0341 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:43:40:0342 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:43:40:0343 FuPlugin             fu_plugin_device_registered(dell_dock)
19:43:40:0343 FuPlugin             fu_plugin_device_registered(pci_bcr)
19:43:40:0343 FuPlugin             fu_plugin_device_registered(thunderbolt)
19:43:40:0343 FuPlugin             fu_plugin_device_registered(tpm)
19:43:40:0343 FuDeviceList         ::added 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
19:43:40:0344 FuMain               ADDED:
FuEmmcDevice:
  DeviceId:             0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
  Name:                 DA4032
  Guid:                 8c6f96d4-f406-53fa-84ca-a367cd368dfc ← EMMC\DA4032
  Guid:                 add792f2-7053-5638-80e7-20987fd16769 ← EMMC\0069&0256
  Guid:                 5500994c-1b73-52b4-acf4-bb574b6f3029 ← EMMC\0069&0256&DA4032
  Serial:               0xb2161c15
  Plugin:               emmc
  Protocol:             org.jedec.mmc
  Flags:                internal|updatable|registered
  VendorId:             EMMC:0x000045
  Version:              0x3034313430363139
  VersionFormat:        number
  Icon:                 media-memory
  Created:              2021-12-13
  PhysicalId:           DEVPATH=/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001
  BackendId:            /sys/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001/block/mmcblk2
  PossiblePlugin:       ata
  PossiblePlugin:       emmc
  InternalFlags:        is-open
  SysfsPath:            /sys/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001/block/mmcblk2
  Subsystem:            block
  DeviceFile:           /dev/mmcblk2
  SectorSize:           512

19:43:40:0345 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:43:40:0345 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:43:40:0459 FuEngine             Emitting PropertyChanged('Status'='idle')
19:43:40:0460 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:43:40:0460 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:43:40:0502 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:43:40:0505 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
19:43:40:0505 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
19:43:40:0546 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
19:43:40:0548 FuEngine             writing motd target /var/cache/fwupd/motd.d/85-fwupd
WARNING: UEFI capsule updates not available or enabled in firmware setup
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
WARNING: This package has not been validated, it may not work properly.
19:43:40:0561 FuMain               FuEmmcDevice:
  DeviceId:             0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
  Name:                 DA4032
  Guid:                 8c6f96d4-f406-53fa-84ca-a367cd368dfc ← EMMC\DA4032
  Guid:                 add792f2-7053-5638-80e7-20987fd16769 ← EMMC\0069&0256
  Guid:                 5500994c-1b73-52b4-acf4-bb574b6f3029 ← EMMC\0069&0256&DA4032
  Serial:               0xb2161c15
  Plugin:               emmc
  Protocol:             org.jedec.mmc
  Flags:                internal|updatable|registered
  VendorId:             EMMC:0x000045
  Version:              0x3034313430363139
  VersionFormat:        number
  Icon:                 media-memory
  Created:              2021-12-13

19:43:40:0561 FuMain               FuMmDevice:
  DeviceId:             976c4a39e87f61e6940ea6a8d39c583cfa99615f
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
  Summary:              Mobile broadband device
  Plugin:               modem_manager
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  VendorId:             USB:0x2C7C
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  Created:              2021-12-13

19:43:40:0567 FuPlugin             destroy(synaptics_mst)
19:43:40:0567 FuPlugin             destroy(logind)
19:43:40:0568 FuPlugin             destroy(pci_mei)
19:43:40:0568 FuPlugin             destroy(upower)
19:43:40:0569 FuPlugin             destroy(modem_manager)
19:43:40:0571 FuPlugin             destroy(linux_lockdown)
19:43:40:0572 FuPlugin             destroy(linux_swap)
19:43:40:0572 FuPlugin             destroy(powerd)
19:43:40:0573 FuPlugin             destroy(tpm)
19:43:40:0573 FuPlugin             destroy(linux_tainted)
19:43:40:0575 FuPlugin             destroy(uefi_capsule)
```

@hughsie 's patch behaves the same:

```
20:05:12:0281 FuDebug              Verbose debugging enabled (on console 1)
20:05:12:0283 FuMain               locked /run/lock/fwupdtool
20:05:12:0284 FuConfig             loading config values from /etc/fwupd/daemon.conf
20:05:12:0284 FuConfig             using autodetected max archive size 18.4 EB
20:05:12:0286 GLib-GIO             _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
20:05:12:0288 FuRemoteList         loading /usr/share/fwupd/metainfo
20:05:12:0289 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
20:05:12:0289 XbSilo               file: 472a8523-1ccc-39db-1a75-7c8a1ad01802, current:472a8523-1ccc-39db-1a75-7c8a1ad01802, cached: (null)
20:05:12:0290 XbSilo               loading silo with file contents
20:05:12:0291 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor.conf
20:05:12:0291 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs.conf
20:05:12:0293 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs-testing.conf
20:05:12:0294 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor-directory.conf
20:05:12:0295 FuRemoteList         skipping invalid file /etc/fwupd/remotes.d/vendor-directory.conf.apk-new
20:05:12:0295 FuRemoteList         loading remote from /etc/fwupd/remotes.d/fwupd-tests.conf
20:05:12:0296 FuRemoteList         ignoring unfound remote fwupd
20:05:12:0296 FuRemoteList         ordering lvfs-testing=lvfs+1
20:05:12:0297 Jcat                 ignoring GPG-KEY-Linux-Foundation-Firmware as not PKCS-7 certificate
20:05:12:0297 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
20:05:12:0297 Jcat                 trying to load certificate from /etc/pki/fwupd/LVFS-CA.pem
20:05:12:0297 Jcat                 reading /etc/pki/fwupd/LVFS-CA.pem with 1679 bytes
20:05:12:0303 Jcat                 loaded 1 certificates
20:05:12:0303 Jcat                 ignoring GPG-KEY-Linux-Foundation-Metadata as not PKCS-7 certificate
20:05:12:0304 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
20:05:12:0304 Jcat                 trying to load certificate from /etc/pki/fwupd-metadata/LVFS-CA.pem
20:05:12:0304 Jcat                 reading /etc/pki/fwupd-metadata/LVFS-CA.pem with 1679 bytes
20:05:12:0305 Jcat                 loaded 1 certificates
20:05:12:0305 Jcat                 reading /var/lib/fwupd/pki/secret.key with 2459 bytes
20:05:12:0305 Jcat                 reading /var/lib/fwupd/pki/client.pem with 1383 bytes
20:05:12:0305 FuEngine             client certificate now exists: nothing to do
20:05:12:0306 FuHistory            trying to open database '/var/lib/fwupd/pending.db'
20:05:12:0314 FuHistory            got schema version of 7
20:05:12:0315 FuHwids              loading HwId overrides from /etc/fwupd/daemon.conf
20:05:12:0315 FuHwids              not loading HwId overrides from /var/lib/fwupd/daemon.conf
20:05:12:0316 FuHwids              ignoring Manufacturer: no data available
20:05:12:0316 FuHwids              smbios property EnclosureKind=8
20:05:12:0316 FuHwids              ignoring Family: offset bigger than size 6
20:05:12:0316 FuHwids              smbios property ProductName=Pine64 PinePhone (1.2)
20:05:12:0316 FuHwids              ignoring ProductSku: offset bigger than size 6
20:05:12:0316 FuHwids              ignoring BiosVendor: offset bigger than size 0
20:05:12:0316 FuHwids              ignoring BiosVersion: offset bigger than size 0
20:05:12:0316 FuHwids              ignoring BiosMajorRelease: offset bigger than size 0
20:05:12:0316 FuHwids              ignoring BiosMinorRelease: offset bigger than size 0
20:05:12:0316 FuHwids              ignoring FirmwareMajorRelease: offset bigger than size 0
20:05:12:0316 FuHwids              ignoring FirmwareMinorRelease: offset bigger than size 0
20:05:12:0317 FuHwids              ignoring BaseboardManufacturer: offset bigger than size 0
20:05:12:0317 FuHwids              ignoring BaseboardProduct: offset bigger than size 0
20:05:12:0317 FuHwids              HardwareID-0 is not available, not available as 'Manufacturer' unknown
20:05:12:0317 FuHwids              HardwareID-1 is not available, not available as 'Manufacturer' unknown
20:05:12:0317 FuHwids              HardwareID-2 is not available, not available as 'Manufacturer' unknown
20:05:12:0317 FuHwids              HardwareID-3 is not available, not available as 'Manufacturer' unknown
20:05:12:0317 FuHwids              HardwareID-4 is not available, not available as 'Manufacturer' unknown
20:05:12:0317 FuHwids              HardwareID-5 is not available, not available as 'Manufacturer' unknown
20:05:12:0320 FuHwids              HardwareID-6 is not available, not available as 'Manufacturer' unknown
20:05:12:0324 FuHwids              HardwareID-7 is not available, not available as 'Manufacturer' unknown
20:05:12:0328 FuHwids              HardwareID-8 is not available, not available as 'Manufacturer' unknown
20:05:12:0332 FuHwids              HardwareID-9 is not available, not available as 'Manufacturer' unknown
20:05:12:0334 FuHwids              HardwareID-10 is not available, not available as 'Manufacturer' unknown
20:05:12:0334 FuHwids              HardwareID-11 is not available, not available as 'Manufacturer' unknown
20:05:12:0334 FuHwids              HardwareID-12 is not available, not available as 'Manufacturer' unknown
20:05:12:0334 FuHwids              HardwareID-13 is not available, not available as 'Manufacturer' unknown
20:05:12:0334 FuHwids              HardwareID-14 is not available, not available as 'Manufacturer' unknown
20:05:12:0339 FuEngine             building metadata for remote 'vendor-directory'
20:05:12:0340 FuEngine             building metadata for /usr/share/fwupd/remotes.d/vendor/firmware/EG25GGBR07A08M2G_01.002.01.002-recovery.cab
20:05:12:0362 FuCommon             reading /usr/share/fwupd/remotes.d/vendor/firmware/EG25GGBR07A08M2G_01.002.01.002-recovery.cab with 11644303 bytes
20:05:12:0363 FuEngine             Emitting PropertyChanged('Status'='decompressing')
Decompressing…           [-                                      ]20:05:12:0532 FuCabinet            failed to verify EG25GGBR07A08M2G_01.002.01.002.metainfo.xml: no JcatItem
20:05:12:0532 FuCabinet            processing file: EG25GGBR07A08M2G_01.002.01.002.metainfo.xml
20:05:12:0532 XbSilo               compiling 6040e4d37707646f5576d1e9c4be58c2400ebe39:filename=EG25GGBR07A08M2G_01.002.01.002-recovery\EG25GGBR07A08M2G_01.002.01.002.metainfo.xml:prefix=components…
20:05:12:0534 FuCabinet            processing release: EG25GGBR07A08M2G_01.002.01.002
20:05:12:0588 FuEngine             Emitting PropertyChanged('Status'='idle')
Decompressing…           [***************************************]
20:05:12:0597 FuEngine             ignoring: /usr/share/fwupd/remotes.d/vendor/firmware/README.md
20:05:12:0597 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
20:05:12:0598 XbSilo               file: e311220e-9159-3ce8-2a44-4ee8cb9cee68, current:e311220e-9159-3ce8-2a44-4ee8cb9cee68, cached: (null)
20:05:12:0598 XbSilo               loading silo with file contents
20:05:12:0605 FuEngine             1204 components now in silo
20:05:12:0648 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_modem_manager.so)
20:05:12:0649 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_parade_lspcon.so)
20:05:12:0649 FuContext            added udev subsystem watch of i2c
20:05:12:0650 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nvme.so)
20:05:12:0651 FuContext            added udev subsystem watch of nvme
20:05:12:0651 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ebitdo.so)
20:05:12:0654 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_capsule.so)
20:05:12:0655 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_cxaudio.so)
20:05:12:0656 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_fresco_pd.so)
20:05:12:0657 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_pk.so)
20:05:12:0658 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_colorhug.so)
20:05:12:0659 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ata.so)
20:05:12:0659 FuContext            added udev subsystem watch of block
20:05:12:0660 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_elanfp.so)
20:05:12:0662 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logitech_hidpp.so)
20:05:12:0662 FuContext            added udev subsystem watch of hidraw
20:05:12:0663 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_analogix.so)
20:05:12:0664 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_jabra.so)
20:05:12:0666 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dfu.so)
20:05:12:0667 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ccgx.so)
20:05:12:0668 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_lockdown.so)
20:05:12:0669 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_optionrom.so)
20:05:12:0669 FuContext            added udev subsystem watch of pci
20:05:12:0671 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logitech_bulkcontroller.so)
20:05:12:0673 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nordic_hid.so)
20:05:12:0674 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_elantp.so)
20:05:12:0674 FuContext            added udev subsystem watch of i2c-dev
20:05:12:0675 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_rts54hid.so)
20:05:12:0675 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_powerd.so)
20:05:12:0676 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_rts54hub.so)
20:05:12:0677 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_iommu.so)
20:05:12:0677 FuContext            added udev subsystem watch of iommu
20:05:12:0678 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dfu_csr.so)
20:05:12:0679 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_emmc.so)
20:05:12:0680 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_realtek_mst.so)
20:05:12:0681 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_cpu.so)
20:05:12:0682 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_hailuck.so)
20:05:12:0683 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_tainted.so)
20:05:12:0691 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_tpm.so)
20:05:12:0691 FuContext            added udev subsystem watch of tpm
20:05:12:0693 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_bcm57xx.so)
20:05:12:0695 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_fastboot.so)
20:05:12:0696 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_dell_dock.so)
20:05:12:0697 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_ep963x.so)
20:05:12:0698 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_steelseries.so)
20:05:12:0700 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_cape.so)
20:05:12:0701 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_acpi_phat.so)
20:05:12:0702 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_mst.so)
20:05:12:0702 FuContext            added udev subsystem watch of drm
20:05:12:0703 FuContext            added udev subsystem watch of drm_dp_aux_dev
20:05:12:0704 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_recovery.so)
20:05:12:0705 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_nitrokey.so)
20:05:12:0706 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_wacom_raw.so)
20:05:12:0708 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_vli.so)
20:05:12:0709 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pci_bcr.so)
20:05:12:0710 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_goodixmoc.so)
20:05:12:0711 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_superio.so)
20:05:12:0712 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_thelio_io.so)
20:05:12:0713 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_system76_launch.so)
20:05:12:0714 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pci_mei.so)
20:05:12:0715 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_prometheus.so)
20:05:12:0717 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_thunderbolt.so)
20:05:12:0717 FuContext            added udev subsystem watch of thunderbolt
20:05:12:0718 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_pixart_rf.so)
20:05:12:0719 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_upower.so)
20:05:12:0720 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_linux_swap.so)
20:05:12:0723 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_synaptics_rmi.so)
20:05:12:0723 FuContext            added udev subsystem watch of serio
20:05:12:0724 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_logind.so)
20:05:12:0725 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_wacom_usb.so)
20:05:12:0726 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_uefi_dbx.so)
20:05:12:0728 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_cros_ec.so)
20:05:12:0729 FuPlugin             init(/usr/lib/fwupd-plugins-5/libfu_plugin_mtd.so)
20:05:12:0729 FuContext            added udev subsystem watch of mtd
20:05:12:0729 FuPluginList         uefi_capsule [0] to be ordered after upower [0] so promoting to [1]
20:05:12:0729 FuPluginList         uefi_recovery [0] to be ordered after uefi_capsule [1] so promoting to [2]
20:05:12:0729 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
20:05:12:0729 FuPluginList         bcm57xx [0] better than optionrom [0] so bumping to [1]
20:05:12:0730 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
20:05:12:0730 FuPluginList         dell_dock [0] better than synaptics_mst [0] so bumping to [1]
20:05:12:0730 FuPluginList         cannot find plugin 'msr' requested by 'cpu'
20:05:12:0766 XbSilo               attempting to load /var/cache/fwupd/quirks.xmlb
20:05:12:0766 XbSilo               file: 9c131e46-ba78-e0c6-f16b-708123a37fc5, current:9c131e46-ba78-e0c6-f16b-708123a37fc5, cached: (null)
20:05:12:0766 XbSilo               loading silo with file contents
20:05:12:0773 FuContext            battery threshold now 10
20:05:12:0773 FuEngine             Emitting PropertyChanged('Status'='loading')
Loading…                 [ -                                     ]20:05:12:0774 FuPlugin             startup(bios)
20:05:12:0774 FuPlugin             startup(lenovo_thinklmi)
20:05:12:0774 FuEngine             disabling plugin because: failed to startup using lenovo_thinklmi: thinklmi not available
20:05:12:0775 FuPlugin             startup(linux_lockdown)
20:05:12:0775 FuPlugin             startup(linux_swap)
20:05:12:0775 FuPlugin             startup(linux_tainted)
20:05:12:0776 FuPlugin             startup(logind)
20:05:12:0786 FuPlugin             startup(logitech_hidpp)
20:05:12:0787 FuPlugin             startup(modem_manager)
20:05:12:0803 FuPlugin             startup(mtd)
20:05:12:0804 FuPlugin             startup(powerd)
20:05:12:0809 FuEngine             disabling plugin because: failed to startup using powerd: no service that owns the name for org.chromium.PowerManager
20:05:12:0809 FuPlugin             startup(thunderbolt)
20:05:12:0810 FuPlugin             startup(tpm)
20:05:12:0810 FuPlugin             startup(upower)
20:05:12:0819 FuContext            battery state now charging
20:05:12:0819 FuContext            battery level now 99
20:05:12:0819 FuPlugin             startup(uefi_capsule)
20:05:12:0820 FuEngine             disabling plugin because: failed to startup using uefi_capsule: offset bigger than size 0
20:05:12:0820 FuPlugin             startup(uefi_recovery)
20:05:12:0820 FuEngine             disabling plugin because: failed to startup using uefi_recovery: kernel efivars support missing: /sys/firmware/efi/efivars
20:05:12:0820 FuPlugin             coldplug(acpi_phat)
20:05:12:0820 FuEngine             disabling plugin because: failed to coldplug using acpi_phat: Failed to open file “/sys/firmware/acpi/tables/PHAT”: No such file or directory
20:05:12:0820 FuPlugin             coldplug(amt)
20:05:12:0821 FuEngine             disabling plugin because: failed to coldplug using amt: Unable to find a ME interface
20:05:12:0821 FuPlugin             coldplug(bios)
20:05:12:0821 FuPlugin             coldplug(cpu)
20:05:12:0822 FuEngine             disabling plugin because: failed to coldplug using cpu: no <cpuid.h> support
20:05:12:0822 FuPlugin             coldplug(modem_manager)
20:05:12:0828 FuPluginMm           ModemManager 1.18.2 is available
20:05:12:0829 FuPluginMm           valid firmware update combination: fastboot
20:05:12:0831 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

20:05:12:0831 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

20:05:12:0831 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318 ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

20:05:12:0832 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP ⚠
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318 ⚠
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125 ⚠
  Summary:              Mobile broadband device
  Protocol:             com.google.fastboot
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

20:05:12:0832 FuDevice             using 976c4a39e87f61e6940ea6a8d39c583cfa99615f for /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
20:05:12:0832 FuPlugin             emit added from modem_manager: 976c4a39e87f61e6940ea6a8d39c583cfa99615f
20:05:12:0883 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
20:05:12:0887 FuPlugin             fu_plugin_device_registered(dell_dock)
20:05:12:0887 FuPlugin             fu_plugin_device_registered(pci_bcr)
20:05:12:0887 FuPlugin             fu_plugin_device_registered(thunderbolt)
20:05:12:0887 FuPlugin             fu_plugin_device_registered(tpm)
20:05:12:0887 FuPlugin             fu_plugin_device_registered(uefi_pk)
20:05:12:0888 FuDeviceList         ::added 976c4a39e87f61e6940ea6a8d39c583cfa99615f
20:05:12:0888 FuMain               ADDED:
FuMmDevice:
  DeviceId:             976c4a39e87f61e6940ea6a8d39c583cfa99615f
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
  Summary:              Mobile broadband device
  Plugin:               modem_manager
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  VendorId:             USB:0x2C7C
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  Created:              2021-12-13
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
  AtPort:               /dev/ttyUSB2

20:05:12:0929 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
20:05:12:0931 FuPlugin             coldplug(superio)
20:05:12:0931 FuPlugin             coldplug(tpm)
20:05:12:0932 FuPluginTpm          failed to load eventlog: Failed to open file “/sys/kernel/security/tpm0/binary_bios_measurements”: No such file or directory
20:05:12:0932 FuPlugin             coldplug(uefi_dbx)
20:05:12:0932 FuDevice             using 230c8b18-8d9b-53ec-838b-6cfc0383493a for main-system-firmware
20:05:12:0932 FuEngine             disabling plugin because: failed to coldplug using uefi_dbx: Error opening file /sys/firmware/efi/efivars/KEK-8be4df61-93ca-11d2-aa0d-00e098032b8c: No such file or directory
20:05:12:0933 FuPlugin             coldplug(uefi_pk)
20:05:12:0933 FuEngine             disabling plugin because: failed to coldplug using uefi_pk: Error opening file /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c: No such file or directory
20:05:12:0933 FuEngine             using plugins: acpi_dmar, acpi_facp, analogix, ata, bcm57xx, bios, ccgx, colorhug, cros_ec, dell_dock, dfu, dfu_csr, ebitdo, elanfp, elantp, emmc, ep963x, fastboot, fresco_pd, goodixmoc, hailuck, iommu, jabra, linux_lockdown, linux_sleep, linux_swap, linux_tainted, logind, logitech_bulkcontroller, logitech_hidpp, modem_manager, mtd, nitrokey, nordic_hid, nvme, optionrom, parade_lspcon, pci_bcr, pci_mei, pixart_rf, realtek_mst, rts54hid, rts54hub, steelseries, superio, synaptics_cape, synaptics_cxaudio, synaptics_mst, synaptics_prometheus, synaptics_rmi, system76_launch, thelio_io, thunderbolt, tpm, upower, vli, wacom_raw, wacom_usb
20:05:12:0955 FuDevice             no registered custom flag detach-at-fastboot-has-response on FuUsbDevice
20:05:13:0150 FuEngine             failed to add device /sys/devices/platform/soc/1c0f000.mmc/mmc_host/mmc0/mmc0:1234/block/mmcblk0: failed get ffu_capable for (null)
20:05:13:0174 FuDevice             using 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7 for DEVPATH=/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001
20:05:13:0179 FuPlugin             emit added from emmc: 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
20:05:13:0211 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
20:05:13:0211 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
20:05:13:0213 FuPlugin             fu_plugin_device_registered(dell_dock)
20:05:13:0213 FuPlugin             fu_plugin_device_registered(pci_bcr)
20:05:13:0213 FuPlugin             fu_plugin_device_registered(thunderbolt)
20:05:13:0213 FuPlugin             fu_plugin_device_registered(tpm)
20:05:13:0213 FuDeviceList         ::added 0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
20:05:13:0214 FuMain               ADDED:
FuEmmcDevice:
  DeviceId:             0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
  Name:                 DA4032
  Guid:                 8c6f96d4-f406-53fa-84ca-a367cd368dfc ← EMMC\DA4032
  Guid:                 add792f2-7053-5638-80e7-20987fd16769 ← EMMC\0069&0256
  Guid:                 5500994c-1b73-52b4-acf4-bb574b6f3029 ← EMMC\0069&0256&DA4032
  Serial:               0xb2161c15
  Plugin:               emmc
  Protocol:             org.jedec.mmc
  Flags:                internal|updatable|registered
  VendorId:             EMMC:0x000045
  Version:              0x3034313430363139
  VersionFormat:        number
  Icon:                 media-memory
  Created:              2021-12-13
  PhysicalId:           DEVPATH=/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001
  BackendId:            /sys/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001/block/mmcblk2
  PossiblePlugin:       ata
  PossiblePlugin:       emmc
  InternalFlags:        is-open
  SysfsPath:            /sys/devices/platform/soc/1c11000.mmc/mmc_host/mmc2/mmc2:0001/block/mmcblk2
  Subsystem:            block
  DeviceFile:           /dev/mmcblk2
  SectorSize:           512

20:05:13:0214 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
20:05:13:0215 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
20:05:13:0325 FuEngine             Emitting PropertyChanged('Status'='idle')
Loading…                 [***************************************]
20:05:13:0326 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
20:05:13:0327 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
20:05:13:0368 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
20:05:13:0371 XbSilo               ignoring for OR statement: indexed string '8c6f96d4-f406-53fa-84ca-a367cd368dfc' was unfound
20:05:13:0371 XbSilo               ignoring for OR statement: indexed string 'add792f2-7053-5638-80e7-20987fd16769' was unfound
20:05:13:0414 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
20:05:13:0416 FuEngine             writing motd target /var/cache/fwupd/motd.d/85-fwupd
WARNING: UEFI capsule updates not available or enabled in firmware setup
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
WARNING: This package has not been validated, it may not work properly.
20:05:13:0434 FuMain               FuEmmcDevice:
  DeviceId:             0e0c93c8b4bb222157feedbde8f863e23bd1a8f7
  Name:                 DA4032
  Guid:                 8c6f96d4-f406-53fa-84ca-a367cd368dfc ← EMMC\DA4032
  Guid:                 add792f2-7053-5638-80e7-20987fd16769 ← EMMC\0069&0256
  Guid:                 5500994c-1b73-52b4-acf4-bb574b6f3029 ← EMMC\0069&0256&DA4032
  Serial:               0xb2161c15
  Plugin:               emmc
  Protocol:             org.jedec.mmc
  Flags:                internal|updatable|registered
  VendorId:             EMMC:0x000045
  Version:              0x3034313430363139
  VersionFormat:        number
  Icon:                 media-memory
  Created:              2021-12-13

20:05:13:0434 FuMain               FuMmDevice:
  DeviceId:             976c4a39e87f61e6940ea6a8d39c583cfa99615f
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
  Summary:              Mobile broadband device
  Plugin:               modem_manager
  Protocol:             com.google.fastboot
  Flags:                updatable|supported|registered|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  VendorId:             USB:0x2C7C
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  Created:              2021-12-13

20:05:13:0440 FuPlugin             destroy(synaptics_mst)
20:05:13:0441 FuPlugin             destroy(logind)
20:05:13:0441 FuPlugin             destroy(pci_mei)
20:05:13:0441 FuPlugin             destroy(upower)
20:05:13:0442 FuPlugin             destroy(modem_manager)
20:05:13:0445 FuPlugin             destroy(linux_lockdown)
20:05:13:0446 FuPlugin             destroy(linux_swap)
20:05:13:0446 FuPlugin             destroy(powerd)
20:05:13:0451 FuPlugin             destroy(tpm)
20:05:13:0457 FuPlugin             destroy(linux_tainted)
20:05:13:0459 FuPlugin             destroy(uefi_capsule)

```

**Comment by hughsie** [comment]
@DylanVanAssche can you try my version please :)

**Comment by DylanVanAssche** [comment]
@hughsie I tried both, logs of both are in the comment, I added a MarkDown title to better differentiate.

**Comment by hughsie** [comment]
Hah, we're both wrong; I don't think you need either additional PR. The device is coming up with `USB\VID_2C7C&PID_0125` so it should have the instance IDs of the subclass, and will get the quirk added itself. The clue is in the:

    20:05:12:0832 FuDevice             no FuContext assigned for FuMmDevice:
      Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125 ⚠

See the little ⚠? That means the context was not assigned and the quirks can't work when the instance ID is set up. Can you try https://github.com/fwupd/fwupd/pull/4079 please?

**Comment by DylanVanAssche** [comment]
@hughsie Your latest patch works great! Thanks! I successfully did an upgrade now :)
However, after the update, the modem gets replugged in and these warnings show up again:

```
08:07:56:0906 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Summary:              Mobile broadband device
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

08:07:56:0906 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Summary:              Mobile broadband device
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

08:07:56:0907 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9
  Summary:              Mobile broadband device
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

08:07:56:0911 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3
  Summary:              Mobile broadband device
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid

08:07:56:0911 FuDevice             no FuContext assigned for FuMmDevice:
  Name:                 QUECTEL Mobile Broadband Module
  Guid:                 db379a33-254f-5140-b37e-d36ae7e5c039
  Guid:                 c33a4560-8681-55b6-bbb6-85258f2de149
  Guid:                 1a2996cb-f86e-5583-a464-e1b96e1c6ae9
  Guid:                 587bf468-6859-5522-93a7-6cce552a0aa3
  Guid:                 22ae45db-f68e-5c55-9c02-4557dca238ec
  Summary:              Mobile broadband device
  Flags:                updatable|use-runtime-version
  Vendor:               QUALCOMM INCORPORATED
  Version:              EG25GGBR07A08M2G - 05010820
  VersionFormat:        plain
  Icon:                 network-modem
  PhysicalId:           /sys/devices/platform/soc/1c1b000.usb/usb2/2-1
  InternalFlags:        replug-match-guid
```

**Comment by DylanVanAssche** [comment]
I fixed a small issue in my patches as well and renamed the flag as the default behavior, without the flag, is to expect a response.

**Review by hughsie — APPROVED** [review]
Looks good to me, but I'd really like @aleksander0m to give it a sanity check too.

**Comment by aleksander0m** [comment]
> Looks good to me, but I'd really like @aleksander0m to give it a sanity check too.

My only concern is not about the patch itself, it's about how this is supposed to work. Are these changes exclusively done for manual installation of hand crafted CAB files? I don't think anyone but Quectel is capable of providing official firmware for these modules via LVFS, and if I'm not mistaken, Quectel is not involved here?

@ivanmikh can you confirm, and, can you ask what would be the official comment from Quectel in this regard? Being a non-official plugin support, I also wonder if Quectel would have comments about the changes in this MR; I think @ivanmikh should also be involved in reviewing/testing this. Maybe you two can sync off-github to share the test CAB files you're using to test this?

And my completely personal opinion here; I would definitely allow this kind of plugin even if there is not going to be "upstream" LVFS support; I'm sure this will be nicely integrated in postmarketos, even if not fully clear how the hand crafted CAB files are going to be provided.

**Comment by DylanVanAssche** [comment]
> My only concern is not about the patch itself, it's about how this is supposed to work. Are these changes exclusively done for manual installation of hand crafted CAB files? I don't think anyone but Quectel is capable of providing official firmware for these modules via LVFS, and if I'm not mistaken, Quectel is not involved here?

Quectel is not involved here, that's right. Currently these CAB files are handcrafted and everything is tested with a `vendor-directory` approach as I don't think postmarketOS or any other organization can upload to LVFS without approval of Quectel.

> @ivanmikh can you confirm, and, can you ask what would be the official comment from Quectel in this regard? Being a non-official plugin support, I also wonder if Quectel would have comments about the changes in this MR; I think @ivanmikh should also be involved in reviewing/testing this. Maybe you two can sync off-github to share the test CAB files you're using to test this?

I would be happy to sync off-github about this, feel free to send me a message.
If Quectel wants to upload their firmware to LVFS that would be great.

> And my completely personal opinion here; I would definitely allow this kind of plugin even if there is not going to be "upstream" LVFS support; I'm sure this will be nicely integrated in postmarketos, even if not fully clear how the hand crafted CAB files are going to be provided.

Indeed, tests are performed on postmarketOS running on a PinePhone. Since there are no CAB files on LVFS for this modem, we are still investigating how to provide these. We found the `vendor-directory` approach of fwupd which allows us to dump these in a directory and fwupd would use this as a local remote.

**Comment by ivanmikh** [comment]
> @ivanmikh can you confirm, and, can you ask what would be the official comment from Quectel in this regard? Being a non-official plugin support, I also wonder if Quectel would have comments about the changes in this MR; I think @ivanmikh should also be involved in reviewing/testing this. Maybe you two can sync off-github to share the test CAB files you're using to test this?

I am personally really glad to see more support for Quectel modems in fwupd, we definitely need that. Regarding Quectel position, EG25-G firmware update is based on fastboot and this MR adds some quirks and workarounds to make it work, so it does not expose anything sensitive as far as I understand.

> I would be happy to sync off-github about this, feel free to send me a message.
If Quectel wants to upload their firmware to LVFS that would be great.

We do not upload any firmware publicly to LVFS usually, that is the customer's responsibility. If postmarketOS is interested in maintaining an LVFS server with Quectel EG25G firmware, I can find information on what is needed to do that.
Quectel releases firmware packages for OTA updates for almost all the customers.

I feel that postmarketOS maintaining an LVFS server would be a better solution here, but I do not think Quectel will get in a way of you using hand-crafted CAB files with `vendor-directory`.

**Comment by hughsie** [comment]
> If postmarketOS is interested in maintaining an LVFS server with Quectel EG25G firmware

I'd much rather see postmarketOS upload the firmware to the actual LVFS; then the files are checked signed and also available to other people. Of course, postmarketOS needs to ave permission to redistribute the firmware in this way. If this is something we should do (and I really recommend that it would be a good thing to _try_ and do) please send me an email off-github and cc the appropriate people to get this set up.

**Comment by ivanmikh** [comment]
> > If postmarketOS is interested in maintaining an LVFS server with Quectel EG25G firmware
> 
> 
> 
> I'd much rather see postmarketOS upload the firmware to the actual LVFS; then the files are checked, signed and also available to other people. Of course, postmarketOS needs to has permission to redistribute the firmware in this way. If this is something we should do (and I really recommend that it would be a good thing to _try_ and do) please send me an email off-github and cc the appropriate people to get this set up.
> 
> 

Yep, sorry I phrased that wrong. I meant postmarketOS uploading firmware to the actual LVFS.

I will try to get info on what is needed from Quectel side.

**Comment by DylanVanAssche** [comment]
@hughsie @ivanmikh @aleksander0m 

I want to clarify that postmarketOS is a regular distro like Debian, we're *not* customers of Quectel.
We work on mobile devices in this distro such as the Pine64 PinePhone and Pine64 PinePhone Pro.
Pine64 is a Quectel customer though as they buy Quectel EG25-G chips from Quectel.
IMO, Pine64 would be the one under which 'name' the firmware is uploaded then to LVFS, not postmarketOS.

Let me contact the Pine64 people first to see how they see it.

**Comment by ivanmikh** [comment]
> IMO, Pine64 would be the one under which 'name' the firmware is uploaded then to LVFS, not postmarketOS.

I need to correct my mistake here: only Quectel is allowed to upload the firmware to the LVFS server. I think it is an LVFS policy, please correct me if I am wrong @hughsie 

Anyway, I think it should be possible for us to upload EG25 firmware to the LVFS, we have started an internal discussion about that thanks to @aleksander0m 

The only issue here is that several Quectel modems share the same VID:PID (2c7c:0125). We might need to add the modem name when building UUID or some other solution to be able to correctly identify suitable firmware update.

**Comment by DylanVanAssche** [comment]
> I need to correct my mistake here: only Quectel is allowed to upload the firmware to the LVFS server. I think it is an LVFS policy, please correct me if I am wrong

DELL also uploads modem firmware to LVFS, but @hughsie can confirm how it works. I am also curious about this.

Just got an e-mail from Pine64 and they don't mind if they need to upload it to LVFS under a Pine64 account.

> The only issue here is that several Quectel modems share the same VID:PID (2c7c:0125). We might need to add the modem name when building UUID or some other solution to be able to correctly identify suitable firmware update.

They have unique firmware version IDs starting with `EG25...` for the EG25 modem, for example.

**Comment by ivanmikh** [comment]
> Just got an e-mail from Pine64 and they don't mind if they need to upload it to LVFS under a Pine64 account.

That's good to know, we might have several options here.

> They have unique firmware version IDs starting with `EG25...` for the EG25 modem, for example.

Yes, but as far as I remember, to match firmware with the correct hardware, UUID are generated from `USB\VID_2C7C&PID_0125&REV_0001` string. In our case several different modem versions will match the same UUID, so we need to add the modem name to the end of the string, e. g.:
`USB\VID_2C7C&PID_0125&REV_0001&EC25GGB`.

**Comment by DylanVanAssche** [comment]
@ivanmikh This is how the modem is identified by fwupd:

```
Summary:            Quectel EG25-G modem
      Current version:    EG25GGBR07A08M2G - 05010820
      Vendor:             QUALCOMM INCORPORATED (USB:0x2C7C)
      GUIDs:              db379a33-254f-5140-b37e-d36ae7e5c039
                          c33a4560-8681-55b6-bbb6-85258f2de149 ← USB\VID_2C7C&PID_0125&REV_0318&CARRIER_ROW_GENERIC_3GPP
                          1a2996cb-f86e-5583-a464-e1b96e1c6ae9 ← USB\VID_2C7C&PID_0125&REV_0318
                          587bf468-6859-5522-93a7-6cce552a0aa3 ← USB\VID_2C7C&PID_0125
                          22ae45db-f68e-5c55-9c02-4557dca238ec ← USB\VID_2C7C
```

Note that `CARRIER_ROW_GENERIC_3GPP` is variable as the modem might pick a different VoLTE profile.

**Comment by hughsie** [comment]
> so we need to add the modem name to the end of the string, e. g.:

Yes, but please do something like: `USB\VID_2C7C&PID_0125&REV_0001&NAME_EC25GGB` as then we know what it is.

**Comment by hughsie** [comment]
> I need to correct my mistake here: only Quectel is allowed to upload the firmware to the LVFS server.

Ohh no, anyone can upload if they have legal permission to do so.

**Comment by hughsie** [comment]
> Pine64 is a Quectel customer

If someone from Pine64 can email me with the required bits we can start the process! https://lvfs.readthedocs.io/en/latest/apply.html

**Comment by ivanmikh** [comment]
> Ohh no, anyone can upload if they have legal permission to do so.

Good to know!

> If someone from Pine64 can email me with the required bits we can start the process! https://lvfs.readthedocs.io/en/latest/apply.html

Great. Team at Pine64 probably have their own contacts in Quectel, but if anything needed from Quectel side feel free to contact me as well.
